-- 005: el catalogo de referencia -monedas (ISO 4217) y paises (ISO 3166-1)-
-- viaja con las migraciones.
--
-- Hasta ahora lo cargaba solo database/seed.php, que es de desarrollo (borra
-- toda la base): una base de produccion creada con las migraciones quedaba con
-- paises y monedas vacios, y como clientes.pais_codigo es NOT NULL y apunta a
-- paises, no se podia dar de alta ni un cliente. (La 001 dice que las tasas las
-- carga el seed; desde esta migracion las carga ella, y el seed las usa.)
--
-- ON CONFLICT DO NOTHING: una base que ya tiene el catalogo (la de desarrollo, o
-- una cuyas tasas se actualizaron a mano) no pierde ni una fila.
--
-- tasa_a_usd = cuantos USD vale 1 unidad de esa moneda (monto * tasa_a_usd da el
-- equivalente en USD). Son tasas estaticas ilustrativas, no un feed en vivo: en
-- produccion hay que reemplazarlas por las reales antes de confiar en los
-- reportes consolidados en USD:
--     UPDATE monedas SET tasa_a_usd = ... WHERE codigo = '...';
--
-- Un pais o una moneda nuevos, o una correccion, van en una migracion nueva:
-- esta ya corrio en las bases existentes.

INSERT INTO monedas (codigo, nombre, simbolo, tasa_a_usd) VALUES
    ('USD', 'Dolar estadounidense', '$', 1.0),
    ('CAD', 'Dolar canadiense', 'CA$', 0.73),
    ('MXN', 'Peso mexicano', 'MX$', 0.058),
    ('GTQ', 'Quetzal guatemalteco', 'Q', 0.13),
    ('BZD', 'Dolar beliceno', 'BZ$', 0.5),
    ('HNL', 'Lempira hondureno', 'L', 0.04),
    ('NIO', 'Cordoba nicaraguense', 'C$', 0.027),
    ('CRC', 'Colon costarricense', '₡', 0.0019),
    ('PAB', 'Balboa panameno', 'B/.', 1.0),
    ('CUP', 'Peso cubano', '$', 0.042),
    ('DOP', 'Peso dominicano', 'RD$', 0.0167),
    ('HTG', 'Gourde haitiano', 'G', 0.0076),
    ('JMD', 'Dolar jamaiquino', 'J$', 0.0064),
    ('TTD', 'Dolar de Trinidad y Tobago', 'TT$', 0.147),
    ('BSD', 'Dolar bahameno', 'B$', 1.0),
    ('BBD', 'Dolar de Barbados', 'Bds$', 0.5),
    ('XCD', 'Dolar del Caribe Oriental', 'EC$', 0.37),
    ('COP', 'Peso colombiano', 'CO$', 0.00025),
    ('VES', 'Bolivar venezolano', 'Bs.', 0.027),
    ('PEN', 'Sol peruano', 'S/', 0.27),
    ('BOB', 'Boliviano', 'Bs', 0.145),
    ('BRL', 'Real brasileno', 'R$', 0.2),
    ('PYG', 'Guarani paraguayo', '₲', 0.00013),
    ('UYU', 'Peso uruguayo', '$U', 0.025),
    ('ARS', 'Peso argentino', 'AR$', 0.0008),
    ('CLP', 'Peso chileno', 'CL$', 0.001),
    ('GYD', 'Dolar guyanes', 'G$', 0.0048),
    ('SRD', 'Dolar surinames', 'Sr$', 0.028),
    ('EUR', 'Euro', '€', 1.08),
    ('GBP', 'Libra esterlina', '£', 1.27),
    ('CHF', 'Franco suizo', 'CHF', 1.13),
    ('NOK', 'Corona noruega', 'kr', 0.092),
    ('SEK', 'Corona sueca', 'kr', 0.095),
    ('DKK', 'Corona danesa', 'kr', 0.145),
    ('ISK', 'Corona islandesa', 'kr', 0.0072),
    ('PLN', 'Zloty polaco', 'zł', 0.25),
    ('CZK', 'Corona checa', 'Kč', 0.043),
    ('HUF', 'Forinto hungaro', 'Ft', 0.0027),
    ('RON', 'Leu rumano', 'lei', 0.22),
    ('BGN', 'Lev bulgaro', 'лв', 0.55),
    ('RSD', 'Dinar serbio', 'дин', 0.0092),
    ('BAM', 'Marco convertible', 'KM', 0.55),
    ('MKD', 'Denar macedonio', 'ден', 0.018),
    ('ALL', 'Lek albanes', 'L', 0.011),
    ('MDL', 'Leu moldavo', 'L', 0.056),
    ('UAH', 'Grivna ucraniana', '₴', 0.024),
    ('BYN', 'Rublo bielorruso', 'Br', 0.0031),
    ('RUB', 'Rublo ruso', '₽', 0.01),
    ('TRY', 'Lira turca', '₺', 0.029),
    ('GEL', 'Lari georgiano', '₾', 0.37),
    ('AMD', 'Dram armenio', '֏', 0.0026),
    ('AZN', 'Manat azerbaiyano', '₼', 0.59),
    ('EGP', 'Libra egipcia', 'E£', 0.02),
    ('LYD', 'Dinar libio', 'ل.د', 0.206),
    ('TND', 'Dinar tunecino', 'د.ت', 0.32),
    ('DZD', 'Dinar argelino', 'د.ج', 0.0075),
    ('MAD', 'Dirham marroqui', 'د.م.', 0.099),
    ('SDG', 'Libra sudanesa', 'ج.س.', 0.0017),
    ('SSP', 'Libra sursudanesa', 'SSP', 0.0008),
    ('ETB', 'Birr etiope', 'Br', 0.0088),
    ('ERN', 'Nakfa eritreo', 'Nfk', 0.067),
    ('DJF', 'Franco yibutiano', 'Fdj', 0.0056),
    ('SOS', 'Chelin somali', 'Sh', 0.0017),
    ('KES', 'Chelin keniano', 'KSh', 0.0078),
    ('UGX', 'Chelin ugandes', 'USh', 0.00027),
    ('TZS', 'Chelin tanzano', 'TSh', 0.00039),
    ('RWF', 'Franco ruandes', 'FRw', 0.00071),
    ('BIF', 'Franco burundes', 'FBu', 0.00035),
    ('CDF', 'Franco congoleno', 'FC', 0.00035),
    ('XAF', 'Franco CFA (Africa Central)', 'FCFA', 0.00165),
    ('NGN', 'Naira nigeriana', '₦', 0.00062),
    ('GHS', 'Cedi ghanes', 'GH₵', 0.068),
    ('XOF', 'Franco CFA (Africa Occidental)', 'CFA', 0.00165),
    ('GNF', 'Franco guineano', 'FG', 0.00012),
    ('SLE', 'Leone (nuevo)', 'Le', 0.044),
    ('LRD', 'Dolar liberiano', 'L$', 0.0052),
    ('GMD', 'Dalasi gambiano', 'D', 0.014),
    ('CVE', 'Escudo caboverdiano', '$', 0.0098),
    ('MRU', 'Uguiya mauritana', 'UM', 0.025),
    ('ZAR', 'Rand sudafricano', 'R', 0.054),
    ('NAD', 'Dolar namibio', 'N$', 0.054),
    ('BWP', 'Pula botsuanesa', 'P', 0.074),
    ('ZWL', 'Dolar zimbabuense', 'Z$', 0.0027),
    ('ZMW', 'Kwacha zambiano', 'ZK', 0.037),
    ('MWK', 'Kwacha malawiano', 'MK', 0.00058),
    ('MZN', 'Metical mozambiqueno', 'MT', 0.0157),
    ('AOA', 'Kwanza angoleno', 'Kz', 0.0011),
    ('SZL', 'Lilangeni suazi', 'L', 0.054),
    ('LSL', 'Loti lesotense', 'L', 0.054),
    ('MGA', 'Ariary malgache', 'Ar', 0.00022),
    ('MUR', 'Rupia mauriciana', '₨', 0.021),
    ('SCR', 'Rupia seychellense', '₨', 0.072),
    ('KMF', 'Franco comorense', 'CF', 0.0022),
    ('STN', 'Dobra santotomense', 'Db', 0.043),
    ('SAR', 'Riyal saudi', '﷼', 0.267),
    ('AED', 'Dirham de EAU', 'د.إ', 0.272),
    ('QAR', 'Riyal catari', 'ر.ق', 0.2747),
    ('KWD', 'Dinar kuwaiti', 'د.ك', 3.25),
    ('BHD', 'Dinar bahreini', '.د.ب', 2.65),
    ('OMR', 'Rial omani', 'ر.ع.', 2.6),
    ('YER', 'Rial yemeni', '﷼', 0.004),
    ('IQD', 'Dinar iraqui', 'ع.د', 0.00076),
    ('IRR', 'Rial irani', '﷼', 0.000024),
    ('SYP', 'Libra siria', '£S', 0.00008),
    ('JOD', 'Dinar jordano', 'د.ا', 1.41),
    ('LBP', 'Libra libanesa', 'ل.ل', 0.0000112),
    ('ILS', 'Nuevo shekel israeli', '₪', 0.27),
    ('KZT', 'Tenge kazajo', '₸', 0.0021),
    ('UZS', 'Som uzbeko', 'so''m', 0.000078),
    ('TMT', 'Manat turcomano', 'm', 0.286),
    ('TJS', 'Somoni tayiko', 'SM', 0.094),
    ('KGS', 'Som kirguizo', 'с', 0.0115),
    ('AFN', 'Afgani afgano', '؋', 0.0142),
    ('INR', 'Rupia india', '₹', 0.012),
    ('PKR', 'Rupia pakistani', '₨', 0.0036),
    ('BDT', 'Taka bangladesi', '৳', 0.0084),
    ('LKR', 'Rupia esrilanquesa', '₨', 0.0034),
    ('NPR', 'Rupia nepali', '₨', 0.0075),
    ('BTN', 'Ngultrum butanes', 'Nu.', 0.012),
    ('MVR', 'Rufiyaa maldiva', 'Rf', 0.065),
    ('CNY', 'Yuan chino', '¥', 0.14),
    ('JPY', 'Yen japones', '¥', 0.0067),
    ('KRW', 'Won surcoreano', '₩', 0.00072),
    ('KPW', 'Won norcoreano', '₩', 0.0011),
    ('MNT', 'Tugrik mongol', '₮', 0.00029),
    ('TWD', 'Nuevo dolar taiwanes', 'NT$', 0.031),
    ('HKD', 'Dolar de Hong Kong', 'HK$', 0.128),
    ('MOP', 'Pataca de Macao', 'MOP$', 0.124),
    ('THB', 'Baht tailandes', '฿', 0.028),
    ('VND', 'Dong vietnamita', '₫', 0.00004),
    ('IDR', 'Rupia indonesia', 'Rp', 0.000062),
    ('MYR', 'Ringgit malayo', 'RM', 0.21),
    ('SGD', 'Dolar de Singapur', 'S$', 0.74),
    ('PHP', 'Peso filipino', '₱', 0.017),
    ('MMK', 'Kyat birmano', 'K', 0.00048),
    ('KHR', 'Riel camboyano', '៛', 0.00025),
    ('LAK', 'Kip laosiano', '₭', 0.000046),
    ('BND', 'Dolar de Brunei', 'B$', 0.74),
    ('AUD', 'Dolar australiano', 'A$', 0.65),
    ('NZD', 'Dolar neozelandes', 'NZ$', 0.6),
    ('PGK', 'Kina papuana', 'K', 0.25),
    ('FJD', 'Dolar fiyiano', 'FJ$', 0.44),
    ('SBD', 'Dolar salomonense', 'SI$', 0.12),
    ('VUV', 'Vatu vanuatuense', 'VT', 0.0084),
    ('WST', 'Tala samoana', 'WS$', 0.37),
    ('TOP', 'Paanga tongana', 'T$', 0.42)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO paises (codigo, nombre, moneda_codigo) VALUES
    -- America del Norte
    ('US', 'Estados Unidos', 'USD'),
    ('CA', 'Canada', 'CAD'),
    ('MX', 'Mexico', 'MXN'),
    -- America Central
    ('GT', 'Guatemala', 'GTQ'),
    ('BZ', 'Belice', 'BZD'),
    ('HN', 'Honduras', 'HNL'),
    ('SV', 'El Salvador', 'USD'),
    ('NI', 'Nicaragua', 'NIO'),
    ('CR', 'Costa Rica', 'CRC'),
    ('PA', 'Panama', 'PAB'),
    -- Caribe
    ('CU', 'Cuba', 'CUP'),
    ('DO', 'Republica Dominicana', 'DOP'),
    ('HT', 'Haiti', 'HTG'),
    ('JM', 'Jamaica', 'JMD'),
    ('TT', 'Trinidad y Tobago', 'TTD'),
    ('BS', 'Bahamas', 'BSD'),
    ('BB', 'Barbados', 'BBD'),
    ('GD', 'Granada', 'XCD'),
    ('LC', 'Santa Lucia', 'XCD'),
    ('VC', 'San Vicente y las Granadinas', 'XCD'),
    ('AG', 'Antigua y Barbuda', 'XCD'),
    ('KN', 'San Cristobal y Nieves', 'XCD'),
    ('DM', 'Dominica', 'XCD'),
    -- America del Sur
    ('CO', 'Colombia', 'COP'),
    ('VE', 'Venezuela', 'VES'),
    ('EC', 'Ecuador', 'USD'),
    ('PE', 'Peru', 'PEN'),
    ('BO', 'Bolivia', 'BOB'),
    ('BR', 'Brasil', 'BRL'),
    ('PY', 'Paraguay', 'PYG'),
    ('UY', 'Uruguay', 'UYU'),
    ('AR', 'Argentina', 'ARS'),
    ('CL', 'Chile', 'CLP'),
    ('GY', 'Guyana', 'GYD'),
    ('SR', 'Surinam', 'SRD'),
    -- Europa (zona euro)
    ('ES', 'Espana', 'EUR'),
    ('PT', 'Portugal', 'EUR'),
    ('FR', 'Francia', 'EUR'),
    ('DE', 'Alemania', 'EUR'),
    ('IT', 'Italia', 'EUR'),
    ('NL', 'Paises Bajos', 'EUR'),
    ('BE', 'Belgica', 'EUR'),
    ('AT', 'Austria', 'EUR'),
    ('IE', 'Irlanda', 'EUR'),
    ('GR', 'Grecia', 'EUR'),
    ('FI', 'Finlandia', 'EUR'),
    ('LU', 'Luxemburgo', 'EUR'),
    ('MT', 'Malta', 'EUR'),
    ('CY', 'Chipre', 'EUR'),
    ('SI', 'Eslovenia', 'EUR'),
    ('SK', 'Eslovaquia', 'EUR'),
    ('EE', 'Estonia', 'EUR'),
    ('LV', 'Letonia', 'EUR'),
    ('LT', 'Lituania', 'EUR'),
    ('HR', 'Croacia', 'EUR'),
    ('AD', 'Andorra', 'EUR'),
    ('MC', 'Monaco', 'EUR'),
    ('SM', 'San Marino', 'EUR'),
    ('VA', 'Ciudad del Vaticano', 'EUR'),
    ('ME', 'Montenegro', 'EUR'),
    ('XK', 'Kosovo', 'EUR'),
    -- Europa (no euro)
    ('GB', 'Reino Unido', 'GBP'),
    ('CH', 'Suiza', 'CHF'),
    ('NO', 'Noruega', 'NOK'),
    ('SE', 'Suecia', 'SEK'),
    ('DK', 'Dinamarca', 'DKK'),
    ('IS', 'Islandia', 'ISK'),
    ('PL', 'Polonia', 'PLN'),
    ('CZ', 'Republica Checa', 'CZK'),
    ('HU', 'Hungria', 'HUF'),
    ('RO', 'Rumania', 'RON'),
    ('BG', 'Bulgaria', 'BGN'),
    ('RS', 'Serbia', 'RSD'),
    ('BA', 'Bosnia y Herzegovina', 'BAM'),
    ('MK', 'Macedonia del Norte', 'MKD'),
    ('AL', 'Albania', 'ALL'),
    ('MD', 'Moldavia', 'MDL'),
    ('UA', 'Ucrania', 'UAH'),
    ('BY', 'Bielorrusia', 'BYN'),
    ('RU', 'Rusia', 'RUB'),
    ('TR', 'Turquia', 'TRY'),
    ('GE', 'Georgia', 'GEL'),
    ('AM', 'Armenia', 'AMD'),
    ('AZ', 'Azerbaiyan', 'AZN'),
    -- Africa
    ('EG', 'Egipto', 'EGP'),
    ('LY', 'Libia', 'LYD'),
    ('TN', 'Tunez', 'TND'),
    ('DZ', 'Argelia', 'DZD'),
    ('MA', 'Marruecos', 'MAD'),
    ('SD', 'Sudan', 'SDG'),
    ('SS', 'Sudan del Sur', 'SSP'),
    ('ET', 'Etiopia', 'ETB'),
    ('ER', 'Eritrea', 'ERN'),
    ('DJ', 'Yibuti', 'DJF'),
    ('SO', 'Somalia', 'SOS'),
    ('KE', 'Kenia', 'KES'),
    ('UG', 'Uganda', 'UGX'),
    ('TZ', 'Tanzania', 'TZS'),
    ('RW', 'Ruanda', 'RWF'),
    ('BI', 'Burundi', 'BIF'),
    ('CD', 'Republica Democratica del Congo', 'CDF'),
    ('CG', 'Republica del Congo', 'XAF'),
    ('CM', 'Camerun', 'XAF'),
    ('CF', 'Republica Centroafricana', 'XAF'),
    ('TD', 'Chad', 'XAF'),
    ('GA', 'Gabon', 'XAF'),
    ('GQ', 'Guinea Ecuatorial', 'XAF'),
    ('NG', 'Nigeria', 'NGN'),
    ('GH', 'Ghana', 'GHS'),
    ('CI', 'Costa de Marfil', 'XOF'),
    ('SN', 'Senegal', 'XOF'),
    ('ML', 'Mali', 'XOF'),
    ('BF', 'Burkina Faso', 'XOF'),
    ('NE', 'Niger', 'XOF'),
    ('TG', 'Togo', 'XOF'),
    ('BJ', 'Benin', 'XOF'),
    ('GW', 'Guinea-Bisau', 'XOF'),
    ('GN', 'Guinea', 'GNF'),
    ('SL', 'Sierra Leona', 'SLE'),
    ('LR', 'Liberia', 'LRD'),
    ('GM', 'Gambia', 'GMD'),
    ('CV', 'Cabo Verde', 'CVE'),
    ('MR', 'Mauritania', 'MRU'),
    ('ZA', 'Sudafrica', 'ZAR'),
    ('NA', 'Namibia', 'NAD'),
    ('BW', 'Botsuana', 'BWP'),
    ('ZW', 'Zimbabue', 'ZWL'),
    ('ZM', 'Zambia', 'ZMW'),
    ('MW', 'Malaui', 'MWK'),
    ('MZ', 'Mozambique', 'MZN'),
    ('AO', 'Angola', 'AOA'),
    ('SZ', 'Esuatini', 'SZL'),
    ('LS', 'Lesoto', 'LSL'),
    ('MG', 'Madagascar', 'MGA'),
    ('MU', 'Mauricio', 'MUR'),
    ('SC', 'Seychelles', 'SCR'),
    ('KM', 'Comoras', 'KMF'),
    ('ST', 'Santo Tome y Principe', 'STN'),
    -- Oriente Medio
    ('SA', 'Arabia Saudita', 'SAR'),
    ('AE', 'Emiratos Arabes Unidos', 'AED'),
    ('QA', 'Catar', 'QAR'),
    ('KW', 'Kuwait', 'KWD'),
    ('BH', 'Bahrein', 'BHD'),
    ('OM', 'Oman', 'OMR'),
    ('YE', 'Yemen', 'YER'),
    ('IQ', 'Irak', 'IQD'),
    ('IR', 'Iran', 'IRR'),
    ('SY', 'Siria', 'SYP'),
    ('JO', 'Jordania', 'JOD'),
    ('LB', 'Libano', 'LBP'),
    ('IL', 'Israel', 'ILS'),
    ('PS', 'Palestina', 'ILS'),
    -- Asia Central
    ('KZ', 'Kazajistan', 'KZT'),
    ('UZ', 'Uzbekistan', 'UZS'),
    ('TM', 'Turkmenistan', 'TMT'),
    ('TJ', 'Tayikistan', 'TJS'),
    ('KG', 'Kirguistan', 'KGS'),
    ('AF', 'Afganistan', 'AFN'),
    -- Asia del Sur
    ('IN', 'India', 'INR'),
    ('PK', 'Pakistan', 'PKR'),
    ('BD', 'Bangladesh', 'BDT'),
    ('LK', 'Sri Lanka', 'LKR'),
    ('NP', 'Nepal', 'NPR'),
    ('BT', 'Butan', 'BTN'),
    ('MV', 'Maldivas', 'MVR'),
    -- Asia Oriental
    ('CN', 'China', 'CNY'),
    ('JP', 'Japon', 'JPY'),
    ('KR', 'Corea del Sur', 'KRW'),
    ('KP', 'Corea del Norte', 'KPW'),
    ('MN', 'Mongolia', 'MNT'),
    ('TW', 'Taiwan', 'TWD'),
    ('HK', 'Hong Kong', 'HKD'),
    ('MO', 'Macao', 'MOP'),
    -- Sudeste asiatico
    ('TH', 'Tailandia', 'THB'),
    ('VN', 'Vietnam', 'VND'),
    ('ID', 'Indonesia', 'IDR'),
    ('MY', 'Malasia', 'MYR'),
    ('SG', 'Singapur', 'SGD'),
    ('PH', 'Filipinas', 'PHP'),
    ('MM', 'Myanmar', 'MMK'),
    ('KH', 'Camboya', 'KHR'),
    ('LA', 'Laos', 'LAK'),
    ('BN', 'Brunei', 'BND'),
    ('TL', 'Timor Oriental', 'USD'),
    -- Oceania
    ('AU', 'Australia', 'AUD'),
    ('NZ', 'Nueva Zelanda', 'NZD'),
    ('PG', 'Papua Nueva Guinea', 'PGK'),
    ('FJ', 'Fiyi', 'FJD'),
    ('SB', 'Islas Salomon', 'SBD'),
    ('VU', 'Vanuatu', 'VUV'),
    ('WS', 'Samoa', 'WST'),
    ('TO', 'Tonga', 'TOP'),
    ('KI', 'Kiribati', 'AUD'),
    ('TV', 'Tuvalu', 'AUD'),
    ('NR', 'Nauru', 'AUD'),
    ('FM', 'Micronesia', 'USD'),
    ('MH', 'Islas Marshall', 'USD'),
    ('PW', 'Palaos', 'USD')
ON CONFLICT (codigo) DO NOTHING;
