// Loads countries/index.json (one request, generated by `npm run build`) and
// flattens it into rows. Per-country files (countries/{tld}/…) stay available
// for downloads and for the PHP API.
const BUNDLE_URL = new URL("../../countries/index.json", import.meta.url);
const COUNTRY_URL = (tld, file) => new URL(`../../countries/${tld}/${file}`, import.meta.url).href;

export const countryFileUrl = COUNTRY_URL;

export function hydrate(bundle, enrichRow = (row) => row) {
  const rows = [];
  for (const country of bundle.countries) {
    country.laws.forEach((law, index) => {
      rows.push(
        enrichRow({
          ...law,
          country_code: country.code,
          country_name: country.name,
          region: country.region,
          tld: country.tld,
          id: `${country.tld}-${index}`,
        })
      );
    });
  }
  return {
    meta: {
      module: bundle.module,
      version: bundle.version,
      generatedAt: bundle.generatedAt,
      columns: bundle.columns,
    },
    countries: bundle.countries,
    rows,
  };
}

let pending;

/** The bundle is fetched once per page load; revalidated with the server (cheap 304). */
export function loadBundle(enrichRow) {
  pending ??= fetch(BUNDLE_URL, { cache: "no-cache" }).then((response) => {
    if (!response.ok) throw new Error(`HTTP ${response.status} loading ${BUNDLE_URL.pathname}`);
    return response.json();
  });
  return pending.then((bundle) => hydrate(bundle, enrichRow));
}
