// Loads jurisdictions/index.json (one request, generated by `npm run build`) and
// flattens it into rows. Per-jurisdiction files (jurisdictions/{tld}/…) stay
// available for downloads and for the PHP API.
const BUNDLE_URL = new URL("../../jurisdictions/index.json", import.meta.url);
const JURISDICTION_URL = (tld, file) =>
  new URL(`../../jurisdictions/${tld}/${file}`, import.meta.url).href;

export const jurisdictionFileUrl = JURISDICTION_URL;

export function hydrate(bundle, enrichRow = (row) => row) {
  const rows = [];
  for (const jurisdiction of bundle.jurisdictions) {
    jurisdiction.laws.forEach((law, index) => {
      rows.push(
        enrichRow({
          ...law,
          country_code: jurisdiction.code,
          country_name: jurisdiction.name,
          region: jurisdiction.region,
          tld: jurisdiction.tld,
          id: `${jurisdiction.tld}-${index}`,
        })
      );
    });
  }
  return {
    meta: {
      module: bundle.module,
      version: bundle.version,
      generatedAt: bundle.generatedAt,
      columns: bundle.columns,
    },
    jurisdictions: bundle.jurisdictions,
    rows,
  };
}

let pending;

/** The bundle is fetched once per page load; revalidated with the server (cheap 304). */
export function loadBundle(enrichRow) {
  pending ??= fetch(BUNDLE_URL, { cache: "no-cache" }).then((response) => {
    if (!response.ok) throw new Error(`HTTP ${response.status} loading ${BUNDLE_URL.pathname}`);
    return response.json();
  });
  return pending.then((bundle) => hydrate(bundle, enrichRow));
}
