<?php

$adjectivesExpandedSet = [
    'spa' => [
        ['bastardo', 'masculino', 'singular', 'alta'],
        ['bastarda', 'femenino', 'singular', 'alta'],
        ['bastardos', 'masculino', 'plural', 'alta'],
        ['bastardas', 'femenino', 'plural', 'alta'],
        ['inmoral', 'neutro', 'singular', 'media'],
        ['inmorales', 'neutro', 'plural', 'media'],
        ['corrupto', 'masculino', 'singular', 'alta'],
        ['corrupta', 'femenino', 'singular', 'alta'],
        ['corruptos', 'masculino', 'plural', 'alta'],
        ['corruptas', 'femenino', 'plural', 'alta'],
        ['deshonesto', 'masculino', 'singular', 'alta'],
        ['deshonesta', 'femenino', 'singular', 'alta'],
        ['deshonestos', 'masculino', 'plural', 'alta'],
        ['deshonestas', 'femenino', 'plural', 'alta'],
        ['vil', 'neutro', 'singular', 'alta'],
        ['viles', 'neutro', 'plural', 'alta'],
        ['despicable', 'neutro', 'singular', 'alta'],
        ['despicables', 'neutro', 'plural', 'alta'],
        ['perverso', 'masculino', 'singular', 'alta'],
        ['perversa', 'femenino', 'singular', 'alta'],
        ['perversos', 'masculino', 'plural', 'alta'],
        ['perversas', 'femenino', 'plural', 'alta'],
        ['abominable', 'neutro', 'singular', 'media'],
        ['abominables', 'neutro', 'plural', 'media'],
        ['repugnante', 'neutro', 'singular', 'baja'],
        ['repugnantes', 'neutro', 'plural', 'baja'],
        ['asqueroso', 'masculino', 'singular', 'baja'],
        ['asquerosa', 'femenino', 'singular', 'baja'],
        ['asquerosos', 'masculino', 'plural', 'baja'],
        ['asquerosas', 'femenino', 'plural', 'baja'],
        ['repulsivo', 'masculino', 'singular', 'baja'],
        ['repulsiva', 'femenino', 'singular', 'baja'],
        ['repulsivos', 'masculino', 'plural', 'baja'],
        ['repulsivas', 'femenino', 'plural', 'baja'],
        ['nauseabundo', 'masculino', 'singular', 'baja'],
        ['nauseabunda', 'femenino', 'singular', 'baja'],
        ['nauseabundos', 'masculino', 'plural', 'baja'],
        ['nauseabundas', 'femenino', 'plural', 'baja'],
        ['obsceno', 'masculino', 'singular', 'media'],
        ['obscena', 'femenino', 'singular', 'media'],
        ['obscenos', 'masculino', 'plural', 'media'],
        ['obscenas', 'femenino', 'plural', 'media'],
        ['indecente', 'neutro', 'singular', 'media'],
        ['indecentes', 'neutro', 'plural', 'media'],
        ['depravado', 'masculino', 'singular', 'alta'],
        ['depravada', 'femenino', 'singular', 'alta'],
        ['depravados', 'masculino', 'plural', 'alta'],
        ['depravadas', 'femenino', 'plural', 'alta'],
        ['libidinoso', 'masculino', 'singular', 'media'],
        ['libidinosa', 'femenino', 'singular', 'media'],
        ['libidinosos', 'masculino', 'plural', 'media'],
        ['libidinosas', 'femenino', 'plural', 'media'],
        ['lascivo', 'masculino', 'singular', 'media'],
        ['lasciva', 'femenino', 'singular', 'media'],
        ['lascivos', 'masculino', 'plural', 'media'],
        ['lascivas', 'femenino', 'plural', 'media'],
        ['lujurioso', 'masculino', 'singular', 'media'],
        ['lujuriosa', 'femenino', 'singular', 'media'],
        ['lujuriosos', 'masculino', 'plural', 'media'],
        ['lujuriosas', 'femenino', 'plural', 'media'],
        ['salaz', 'neutro', 'singular', 'media'],
        ['salazes', 'neutro', 'plural', 'media'],
        ['promiscuo', 'masculino', 'singular', 'media'],
        ['promiscua', 'femenino', 'singular', 'media'],
        ['promiscuos', 'masculino', 'plural', 'media'],
        ['promiscuas', 'femenino', 'plural', 'media'],
        ['adúltero', 'masculino', 'singular', 'media'],
        ['adúltera', 'femenino', 'singular', 'media'],
        ['adúlteros', 'masculino', 'plural', 'media'],
        ['adúlteras', 'femenino', 'plural', 'media'],
        ['infiel', 'neutro', 'singular', 'media'],
        ['infieles', 'neutro', 'plural', 'media'],
        ['traidor', 'masculino', 'singular', 'alta'],
        ['traidora', 'femenino', 'singular', 'alta'],
        ['traidores', 'masculino', 'plural', 'alta'],
        ['traidoras', 'femenino', 'plural', 'alta'],
        ['desleal', 'neutro', 'singular', 'alta'],
        ['desleales', 'neutro', 'plural', 'alta'],
        ['pérfido', 'masculino', 'singular', 'alta'],
        ['pérfida', 'femenino', 'singular', 'alta'],
        ['pérfidos', 'masculino', 'plural', 'alta'],
        ['pérfidas', 'femenino', 'plural', 'alta'],
        ['falso', 'masculino', 'singular', 'media'],
        ['falsa', 'femenino', 'singular', 'media'],
        ['falsos', 'masculino', 'plural', 'media'],
        ['falsas', 'femenino', 'plural', 'media'],
        ['mentiroso', 'masculino', 'singular', 'alta'],
        ['mentirosa', 'femenino', 'singular', 'alta'],
        ['mentirosos', 'masculino', 'plural', 'alta'],
        ['mentirosas', 'femenino', 'plural', 'alta'],
        ['embustero', 'masculino', 'singular', 'alta'],
        ['embustera', 'femenino', 'singular', 'alta'],
        ['embusteros', 'masculino', 'plural', 'alta'],
        ['embusteras', 'femenino', 'plural', 'alta'],
        ['farsante', 'neutro', 'singular', 'media'],
        ['farsantes', 'neutro', 'plural', 'media'],
        ['charlatán', 'masculino', 'singular', 'media'],
        ['charlatana', 'femenino', 'singular', 'media'],
        ['charlatanes', 'masculino', 'plural', 'media'],
        ['charlatanas', 'femenino', 'plural', 'media'],
        ['estafador', 'masculino', 'singular', 'alta'],
        ['estafadora', 'femenino', 'singular', 'alta'],
        ['estafadores', 'masculino', 'plural', 'alta'],
        ['estafadoras', 'femenino', 'plural', 'alta'],
        ['defraudador', 'masculino', 'singular', 'alta'],
        ['defraudadora', 'femenino', 'singular', 'alta'],
        ['defraudadores', 'masculino', 'plural', 'alta'],
        ['defraudadoras', 'femenino', 'plural', 'alta'],
        ['sinvergüenza', 'neutro', 'singular', 'alta'],
        ['sinvergüenzas', 'neutro', 'plural', 'alta'],
        ['descarado', 'masculino', 'singular', 'media'],
        ['descarada', 'femenino', 'singular', 'media'],
        ['descarados', 'masculino', 'plural', 'media'],
        ['descaradas', 'femenino', 'plural', 'media'],
        ['desvergonzado', 'masculino', 'singular', 'media'],
        ['desvergonzada', 'femenino', 'singular', 'media'],
        ['desvergonzados', 'masculino', 'plural', 'media'],
        ['desvergonzadas', 'femenino', 'plural', 'media'],
        ['atrevido', 'masculino', 'singular', 'baja'],
        ['atrevida', 'femenino', 'singular', 'baja'],
        ['atrevidos', 'masculino', 'plural', 'baja'],
        ['atrevidas', 'femenino', 'plural', 'baja'],
        ['insolente', 'neutro', 'singular', 'media'],
        ['insolentes', 'neutro', 'plural', 'media'],
        ['grosero', 'masculino', 'singular', 'media'],
        ['grosera', 'femenino', 'singular', 'media'],
        ['groseros', 'masculino', 'plural', 'media'],
        ['groseras', 'femenino', 'plural', 'media'],
        ['vulgar', 'neutro', 'singular', 'baja'],
        ['vulgares', 'neutro', 'plural', 'baja'],
        ['ordinario', 'masculino', 'singular', 'baja'],
        ['ordinaria', 'femenino', 'singular', 'baja'],
        ['ordinarios', 'masculino', 'plural', 'baja'],
        ['ordinarias', 'femenino', 'plural', 'baja'],
        ['tosco', 'masculino', 'singular', 'baja'],
        ['tosca', 'femenino', 'singular', 'baja'],
        ['toscos', 'masculino', 'plural', 'baja'],
        ['toscas', 'femenino', 'plural', 'baja'],
        ['basto', 'masculino', 'singular', 'baja'],
        ['basta', 'femenino', 'singular', 'baja'],
        ['bastos', 'masculino', 'plural', 'baja'],
        ['bastas', 'femenino', 'plural', 'baja'],
        ['gañán', 'masculino', 'singular', 'baja'],
        ['gañana', 'femenino', 'singular', 'baja'],
        ['gañanes', 'masculino', 'plural', 'baja'],
        ['gañanas', 'femenino', 'plural', 'baja'],
        ['patán', 'masculino', 'singular', 'media'],
        ['patana', 'femenino', 'singular', 'media'],
        ['patanes', 'masculino', 'plural', 'media'],
        ['patanas', 'femenino', 'plural', 'media'],
        ['rústico', 'masculino', 'singular', 'baja'],
        ['rústica', 'femenino', 'singular', 'baja'],
        ['rústicos', 'masculino', 'plural', 'baja'],
        ['rústicas', 'femenino', 'plural', 'baja'],
        ['campesino', 'masculino', 'singular', 'baja'],
        ['campesina', 'femenino', 'singular', 'baja'],
        ['campesinos', 'masculino', 'plural', 'baja'],
        ['campesinas', 'femenino', 'plural', 'baja'],
        ['ignorante', 'neutro', 'singular', 'media'],
        ['ignorantes', 'neutro', 'plural', 'media'],
        ['analfabeto', 'masculino', 'singular', 'baja'],
        ['analfabeta', 'femenino', 'singular', 'baja'],
        ['analfabetos', 'masculino', 'plural', 'baja'],
        ['analfabetas', 'femenino', 'plural', 'baja'],
        ['estúpido', 'masculino', 'singular', 'alta'],
        ['estúpida', 'femenino', 'singular', 'alta'],
        ['estúpidos', 'masculino', 'plural', 'alta'],
        ['estúpidas', 'femenino', 'plural', 'alta'],
        ['idiota', 'neutro', 'singular', 'alta'],
        ['idiotas', 'neutro', 'plural', 'alta'],
        ['imbécil', 'neutro', 'singular', 'alta'],
        ['imbéciles', 'neutro', 'plural', 'alta'],
        ['retrasado', 'masculino', 'singular', 'alta'],
        ['retrasada', 'femenino', 'singular', 'alta'],
        ['retrasados', 'masculino', 'plural', 'alta'],
        ['retrasadas', 'femenino', 'plural', 'alta'],
        ['débil', 'neutro', 'singular', 'media'],
        ['débiles', 'neutro', 'plural', 'media'],
        ['cobarde', 'neutro', 'singular', 'media'],
        ['cobardes', 'neutro', 'plural', 'media'],
        ['miedoso', 'masculino', 'singular', 'media'],
        ['miedosa', 'femenino', 'singular', 'media'],
        ['miedosos', 'masculino', 'plural', 'media'],
        ['miedosas', 'femenino', 'plural', 'media'],
        ['pusilánime', 'neutro', 'singular', 'media'],
        ['pusilánimes', 'neutro', 'plural', 'media'],
        ['medroso', 'masculino', 'singular', 'media'],
        ['medrosa', 'femenino', 'singular', 'media'],
        ['medrosos', 'masculino', 'plural', 'media'],
        ['medrosas', 'femenino', 'plural', 'media'],
        ['tímido', 'masculino', 'singular', 'baja'],
        ['tímida', 'femenino', 'singular', 'baja'],
        ['tímidos', 'masculino', 'plural', 'baja'],
        ['tímidas', 'femenino', 'plural', 'baja'],
        ['retraído', 'masculino', 'singular', 'baja'],
        ['retraída', 'femenino', 'singular', 'baja'],
        ['retraídos', 'masculino', 'plural', 'baja'],
        ['retraídas', 'femenino', 'plural', 'baja'],
        ['apocado', 'masculino', 'singular', 'baja'],
        ['apocada', 'femenino', 'singular', 'baja'],
        ['apocados', 'masculino', 'plural', 'baja'],
        ['apocadas', 'femenino', 'plural', 'baja'],
        ['encogido', 'masculino', 'singular', 'baja'],
        ['encogida', 'femenino', 'singular', 'baja'],
        ['encogidos', 'masculino', 'plural', 'baja'],
        ['encogidas', 'femenino', 'plural', 'baja'],
        ['humillado', 'masculino', 'singular', 'media'],
        ['humillada', 'femenino', 'singular', 'media'],
        ['humillados', 'masculino', 'plural', 'media'],
        ['humilladas', 'femenino', 'plural', 'media'],
        ['avergonzado', 'masculino', 'singular', 'media'],
        ['avergonzada', 'femenino', 'singular', 'media'],
        ['avergonzados', 'masculino', 'plural', 'media'],
        ['avergonzadas', 'femenino', 'plural', 'media'],
        ['infame', 'neutro', 'singular', 'alta'],
        ['infames', 'neutro', 'plural', 'alta'],
        ['deshonroso', 'masculino', 'singular', 'media'],
        ['deshonrosa', 'femenino', 'singular', 'media'],
        ['deshonrosos', 'masculino', 'plural', 'media'],
        ['deshonrosas', 'femenino', 'plural', 'media'],
        ['deshonrante', 'neutro', 'singular', 'media'],
        ['deshonrantes', 'neutro', 'plural', 'media'],
        ['oprobioso', 'masculino', 'singular', 'media'],
        ['oprobios', 'masculino', 'plural', 'media'],
        ['escarnecedor', 'masculino', 'singular', 'baja'],
        ['escarneced', 'femenino', 'singular', 'baja'],
        ['escarnecedores', 'masculino', 'plural', 'baja'],
        ['escarneced', 'femenino', 'plural', 'baja'],
        ['burlador', 'masculino', 'singular', 'baja'],
        ['burla', 'femenino', 'singular', 'baja'],
        ['burladores', 'masculino', 'plural', 'baja'],
        ['burladoras', 'femenino', 'plural', 'baja'],
        ['satírico', 'masculino', 'singular', 'baja'],
        ['satírica', 'femenino', 'singular', 'baja'],
        ['satíricos', 'masculino', 'plural', 'baja'],
        ['satíricas', 'femenino', 'plural', 'baja'],
        ['irónico', 'masculino', 'singular', 'baja'],
        ['irónica', 'femenino', 'singular', 'baja'],
        ['irónicos', 'masculino', 'plural', 'baja'],
        ['irónicas', 'femenino', 'plural', 'baja'],
        ['mordaz', 'neutro', 'singular', 'baja'],
        ['mordaces', 'neutro', 'plural', 'baja'],
        ['cáustico', 'masculino', 'singular', 'baja'],
        ['cáustica', 'femenino', 'singular', 'baja'],
        ['cáusticos', 'masculino', 'plural', 'baja'],
        ['cáusticas', 'femenino', 'plural', 'baja'],
        ['sarcástico', 'masculino', 'singular', 'baja'],
        ['sarcástica', 'femenino', 'singular', 'baja'],
        ['sarcásticos', 'masculino', 'plural', 'baja'],
        ['sarcásticas', 'femenino', 'plural', 'baja'],
        ['despiadado', 'masculino', 'singular', 'media'],
        ['despiadada', 'femenino', 'singular', 'media'],
        ['despiadados', 'masculino', 'plural', 'media'],
        ['despiadadas', 'femenino', 'plural', 'media'],
        ['cruel', 'neutro', 'singular', 'alta'],
        ['crueles', 'neutro', 'plural', 'alta'],
        ['inhumano', 'masculino', 'singular', 'alta'],
        ['inhumana', 'femenino', 'singular', 'alta'],
        ['inhumanos', 'masculino', 'plural', 'alta'],
        ['inhumanas', 'femenino', 'plural', 'alta'],
        ['diabólico', 'masculino', 'singular', 'alta'],
        ['diabólica', 'femenino', 'singular', 'alta'],
        ['diabólicos', 'masculino', 'plural', 'alta'],
        ['diabólicas', 'femenino', 'plural', 'alta'],
        ['satánico', 'masculino', 'singular', 'alta'],
        ['satánica', 'femenino', 'singular', 'alta'],
        ['satánicos', 'masculino', 'plural', 'alta'],
        ['satánicas', 'femenino', 'plural', 'alta'],
        ['demoníaco', 'masculino', 'singular', 'alta'],
        ['demoníaca', 'femenino', 'singular', 'alta'],
        ['demoniacos', 'masculino', 'plural', 'alta'],
        ['demoniacas', 'femenino', 'plural', 'alta'],
        ['infernal', 'neutro', 'singular', 'alta'],
        ['infernales', 'neutro', 'plural', 'alta'],
        ['condenado', 'masculino', 'singular', 'media'],
        ['condenada', 'femenino', 'singular', 'media'],
        ['condenados', 'masculino', 'plural', 'media'],
        ['condenadas', 'femenino', 'plural', 'media'],
        ['maldito', 'masculino', 'singular', 'media'],
        ['maldita', 'femenino', 'singular', 'media'],
        ['malditos', 'masculino', 'plural', 'media'],
        ['malditas', 'femenino', 'plural', 'media'],
        ['execrable', 'neutro', 'singular', 'media'],
        ['execrables', 'neutro', 'plural', 'media'],
        ['detestable', 'neutro', 'singular', 'media'],
        ['detestables', 'neutro', 'plural', 'media'],
        ['aborrecible', 'neutro', 'singular', 'media'],
        ['aborrecibles', 'neutro', 'plural', 'media'],
        ['odioso', 'masculino', 'singular', 'alta'],
        ['odiosa', 'femenino', 'singular', 'alta'],
        ['odiosos', 'masculino', 'plural', 'alta'],
        ['odiosas', 'femenino', 'plural', 'alta'],
        ['inmundo', 'masculino', 'singular', 'baja'],
        ['inmunda', 'femenino', 'singular', 'baja'],
        ['inmundos', 'masculino', 'plural', 'baja'],
        ['inmundas', 'femenino', 'plural', 'baja'],
        ['sucio', 'masculino', 'singular', 'baja'],
        ['sucia', 'femenino', 'singular', 'baja'],
        ['sucios', 'masculino', 'plural', 'baja'],
        ['sucias', 'femenino', 'plural', 'baja'],
        ['mugriento', 'masculino', 'singular', 'baja'],
        ['mugrienta', 'femenino', 'singular', 'baja'],
        ['mugrientos', 'masculino', 'plural', 'baja'],
        ['mugrientas', 'femenino', 'plural', 'baja'],
        ['cochino', 'masculino', 'singular', 'baja'],
        ['cochina', 'femenino', 'singular', 'baja'],
        ['cochinos', 'masculino', 'plural', 'baja'],
        ['cochinas', 'femenino', 'plural', 'baja'],
        ['puerco', 'masculino', 'singular', 'baja'],
        ['puerca', 'femenino', 'singular', 'baja'],
        ['puercos', 'masculino', 'plural', 'baja'],
        ['puercas', 'femenino', 'plural', 'baja'],
        ['marrano', 'masculino', 'singular', 'baja'],
        ['marrana', 'femenino', 'singular', 'baja'],
        ['marranos', 'masculino', 'plural', 'baja'],
        ['marranas', 'femenino', 'plural', 'baja'],
        ['desaseado', 'masculino', 'singular', 'baja'],
        ['desaseada', 'femenino', 'singular', 'baja'],
        ['desaseados', 'masculino', 'plural', 'baja'],
        ['desaseadas', 'femenino', 'plural', 'baja'],
        ['desaliñado', 'masculino', 'singular', 'baja'],
        ['desaliñada', 'femenino', 'singular', 'baja'],
        ['desaliñados', 'masculino', 'plural', 'baja'],
        ['desaliñadas', 'femenino', 'plural', 'baja'],
        ['andrajoso', 'masculino', 'singular', 'baja'],
        ['andrajosa', 'femenino', 'singular', 'baja'],
        ['andrajosos', 'masculino', 'plural', 'baja'],
        ['andrajosas', 'femenino', 'plural', 'baja'],
        ['harapiento', 'masculino', 'singular', 'baja'],
        ['harapienta', 'femenino', 'singular', 'baja'],
        ['harapientos', 'masculino', 'plural', 'baja'],
        ['harapientas', 'femenino', 'plural', 'baja'],
        ['zarrapastroso', 'masculino', 'singular', 'baja'],
        ['zarrapastrosa', 'femenino', 'singular', 'baja'],
        ['zarrapastrosos', 'masculino', 'plural', 'baja'],
        ['zarrapastrosas', 'femenino', 'plural', 'baja'],
        ['desgarbado', 'masculino', 'singular', 'baja'],
        ['desgarbada', 'femenino', 'singular', 'baja'],
        ['desgarbados', 'masculino', 'plural', 'baja'],
        ['desgarbadas', 'femenino', 'plural', 'baja'],
        ['torpe', 'neutro', 'singular', 'media'],
        ['torpes', 'neutro', 'plural', 'media'],
        ['patoso', 'masculino', 'singular', 'media'],
        ['patosa', 'femenino', 'singular', 'media'],
        ['patosos', 'masculino', 'plural', 'media'],
        ['patosas', 'femenino', 'plural', 'media'],
        ['zafio', 'masculino', 'singular', 'media'],
        ['zafia', 'femenino', 'singular', 'media'],
        ['zafios', 'masculino', 'plural', 'media'],
        ['zafias', 'femenino', 'plural', 'media'],
        ['traidor', 'masculino', 'singular', 'alta'],
        ['traidora', 'femenino', 'singular', 'alta'],
        ['traidores', 'masculino', 'plural', 'alta'],
        ['traidoras', 'femenino', 'plural', 'alta'],
        ['conspirador', 'masculino', 'singular', 'alta'],
        ['conspiradora', 'femenino', 'singular', 'alta'],
        ['conspiradores', 'masculino', 'plural', 'alta'],
        ['conspiradoras', 'femenino', 'plural', 'alta'],
        ['sedicio', 'masculino', 'singular', 'alta'],
        ['sediciosa', 'femenino', 'singular', 'alta'],
        ['sediciosos', 'masculino', 'plural', 'alta'],
        ['sediciosas', 'femenino', 'plural', 'alta'],
        ['motinero', 'masculino', 'singular', 'alta'],
        ['motinera', 'femenino', 'singular', 'alta'],
        ['motineros', 'masculino', 'plural', 'alta'],
        ['motineras', 'femenino', 'plural', 'alta'],
        ['rebelde', 'neutro', 'singular', 'media'],
        ['rebeldes', 'neutro', 'plural', 'media'],
        ['insurrecto', 'masculino', 'singular', 'alta'],
        ['insurrecto', 'femenino', 'singular', 'alta'],
        ['insurrectos', 'masculino', 'plural', 'alta'],
        ['insurrectos', 'femenino', 'plural', 'alta'],
        ['levantisco', 'masculino', 'singular', 'media'],
        ['levantisca', 'femenino', 'singular', 'media'],
        ['levantiscos', 'masculino', 'plural', 'media'],
        ['levantiscas', 'femenino', 'plural', 'media'],
        ['revoltoso', 'masculino', 'singular', 'media'],
        ['revoltosa', 'femenino', 'singular', 'media'],
        ['revoltosos', 'masculino', 'plural', 'media'],
        ['revoltosas', 'femenino', 'plural', 'media'],
        ['violento', 'masculino', 'singular', 'alta'],
        ['violenta', 'femenino', 'singular', 'alta'],
        ['violentos', 'masculino', 'plural', 'alta'],
        ['violentas', 'femenino', 'plural', 'alta'],
        ['agresivo', 'masculino', 'singular', 'alta'],
        ['agresiva', 'femenino', 'singular', 'alta'],
        ['agresivos', 'masculino', 'plural', 'alta'],
        ['agresivas', 'femenino', 'plural', 'alta'],
        ['brutal', 'neutro', 'singular', 'alta'],
        ['brutales', 'neutro', 'plural', 'alta'],
        ['salvaje', 'neutro', 'singular', 'alta'],
        ['salvajes', 'neutro', 'plural', 'alta'],
        ['feroz', 'neutro', 'singular', 'alta'],
        ['feroces', 'neutro', 'plural', 'alta'],
        ['arrebatado', 'masculino', 'singular', 'media'],
        ['arrebatada', 'femenino', 'singular', 'media'],
        ['arrebatados', 'masculino', 'plural', 'media'],
        ['arrebatadas', 'femenino', 'plural', 'media'],
        ['irreflexivo', 'masculino', 'singular', 'media'],
        ['irreflexiva', 'femenino', 'singular', 'media'],
        ['irreflexivos', 'masculino', 'plural', 'media'],
        ['irreflexivas', 'femenino', 'plural', 'media'],
        ['impulsivo', 'masculino', 'singular', 'media'],
        ['impulsiva', 'femenino', 'singular', 'media'],
        ['impulsivos', 'masculino', 'plural', 'media'],
        ['impulsivas', 'femenino', 'plural', 'media'],
        ['avaro', 'masculino', 'singular', 'media'],
        ['avara', 'femenino', 'singular', 'media'],
        ['avaros', 'masculino', 'plural', 'media'],
        ['avaras', 'femenino', 'plural', 'media'],
        ['codicioso', 'masculino', 'singular', 'media'],
        ['codiciosa', 'femenino', 'singular', 'media'],
        ['codiciosos', 'masculino', 'plural', 'media'],
        ['codiciosas', 'femenino', 'plural', 'media'],
        ['tacaño', 'masculino', 'singular', 'media'],
        ['tacaña', 'femenino', 'singular', 'media'],
        ['tacaños', 'masculino', 'plural', 'media'],
        ['tacañas', 'femenino', 'plural', 'media'],
        ['desprendido', 'masculino', 'singular', 'baja'],
        ['desprendida', 'femenino', 'singular', 'baja'],
        ['desprendidos', 'masculino', 'plural', 'baja'],
        ['desprendidas', 'femenino', 'plural', 'baja'],
        ['generoso', 'masculino', 'singular', 'baja'],
        ['generosa', 'femenino', 'singular', 'baja'],
        ['generosos', 'masculino', 'plural', 'baja'],
        ['generosas', 'femenino', 'plural', 'baja'],
        ['pródigo', 'masculino', 'singular', 'baja'],
        ['pródiga', 'femenino', 'singular', 'baja'],
        ['pródigos', 'masculino', 'plural', 'baja'],
        ['pródiga', 'femenino', 'plural', 'baja'],
        ['envídioso', 'masculino', 'singular', 'media'],
        ['envidiosa', 'femenino', 'singular', 'media'],
        ['envidiosos', 'masculino', 'plural', 'media'],
        ['envidiosas', 'femenino', 'plural', 'media'],
        ['celoso', 'masculino', 'singular', 'media'],
        ['celosa', 'femenino', 'singular', 'media'],
        ['celosos', 'masculino', 'plural', 'media'],
        ['celosas', 'femenino', 'plural', 'media'],
        ['celotípico', 'masculino', 'singular', 'media'],
        ['celotípica', 'femenino', 'singular', 'media'],
        ['celotípicos', 'masculino', 'plural', 'media'],
        ['celotípicas', 'femenino', 'plural', 'media'],
        ['iracundo', 'masculino', 'singular', 'media'],
        ['iracunda', 'femenino', 'singular', 'media'],
        ['iracundos', 'masculino', 'plural', 'media'],
        ['iracundas', 'femenino', 'plural', 'media'],
        ['colérico', 'masculino', 'singular', 'media'],
        ['colérica', 'femenino', 'singular', 'media'],
        ['coléricos', 'masculino', 'plural', 'media'],
        ['colérico', 'femenino', 'plural', 'media'],
        ['arrebatador', 'masculino', 'singular', 'media'],
        ['arrebatadora', 'femenino', 'singular', 'media'],
        ['arrebatadores', 'masculino', 'plural', 'media'],
        ['arrebatadoras', 'femenino', 'plural', 'media'],
        ['temperamental', 'neutro', 'singular', 'media'],
        ['temperamentales', 'neutro', 'plural', 'media'],
        ['bilioso', 'masculino', 'singular', 'media'],
        ['biliosa', 'femenino', 'singular', 'media'],
        ['biliosos', 'masculino', 'plural', 'media'],
        ['biliosas', 'femenino', 'plural', 'media'],
        ['esplénico', 'masculino', 'singular', 'media'],
        ['esplénica', 'femenino', 'singular', 'media'],
        ['esplénicos', 'masculino', 'plural', 'media'],
        ['esplenicas', 'femenino', 'plural', 'media'],
    ],
    'fas' => ['بدجنس', 'بیاخلاق', 'فاسد', 'بددل', 'ذلیل', 'شهوتران', 'متنفراننده', 'متنفراننده', 'فحش', 'نامناسب', 'منحرف', 'سمی', 'خیانتکار', 'بدرفتار', 'دروغ', 'دروغ گو', 'فریب دهنده', 'بدرفتار', 'زنا', 'شهوانی', 'جنسی', 'رفتار بی شرمانه', 'بی قید', 'آزادی خواه', 'بی قید', 'بی شرم', 'جسور', 'شجاع', 'خشن', 'خشن', 'نامناسب', 'عام', 'خشن', 'روستایی', 'دهقان', 'نادان', 'بی سوادی', 'احمق', 'احمق', 'احمق', 'تاخیر', 'ضعیف', 'بزدل', 'ترسو', 'بزدل', 'شرم و حیا', 'بسته', 'تابع', 'تحقیر شده', 'شرمنده', 'شرمنده', 'بی نام و نشان', 'رسوا کننده', 'رسوا کننده', 'مسخره', 'مسخره', 'طنز آمیز', 'ایرونیک', 'تیز تراش', 'خورنده', 'طنز آمیز', 'بی رحم', 'قاسی', 'غیرانسانی', 'ابلیسی', 'شیطانی', 'ابلیسی', 'جهنمی', 'لعنتی', 'لعنتی', 'وحشتناک', 'نفرت انگیز', 'نفرت انگیز', 'نفرت انگیز', 'نفرت انگیز', 'بدبو', 'کثیف', 'کثیف', 'آلوده', 'غفلت', 'بی تفاوت', 'بی تفاوت', 'تنبل', 'بی جان', 'کاهش', 'تخریب', 'بدبخت', 'بدبخت', 'بدبخت', 'بدبخت', 'بدشانس', 'بدبخت', 'بدبخت', 'فاسد', 'رسوا کننده'],
    'urd' => ['غیر شریف', 'بے اخلاق', 'بدعنوان', 'بے ایمان', 'ذلیل', 'کمینہ', 'ناپسندیدہ', 'ناپسندیدہ', 'فحش', 'نامناسب', 'منحرف', 'زہریلا', 'غدار', 'بے وفا', 'جھوٹا', 'جھوٹا', 'فریب دہندہ', 'بے وفا', 'زنا', 'شہوانی', 'جنسی', 'لواہام', 'بے لگام', 'آزادی خواہ', 'بے لگام', 'بے شرم', 'جرات مندانہ', 'بہادرانہ', 'خشن', 'خشن', 'نامناسب', 'عام', 'خشن', 'دیہاتی', 'کسان', 'نادان', 'ان پڑھ', 'احمق', 'احمق', 'احمق', 'تاخیر', 'کمزور', 'بزدل', 'ڈرپوک', 'بزدل', 'شرم و حیا', 'بند', 'تابع', 'ذلیل', 'شرمندہ', 'شرمندہ', 'ناپاک', 'رسوائی کنندہ', 'رسوائی کنندہ', 'مسخرہ', 'مسخرہ', 'طنز آمیز', 'تھکا ہوا', 'تیز', 'کاٹنے والا', 'طنز آمیز', 'بے رحم', 'ظالم', 'غیر انسانی', 'شیطانی', 'شیطانی', 'شیطانی', 'جہنمی', 'ملعون', 'ملعون', 'ہولناک', 'قابلِ نفرت', 'قابلِ نفرت', 'قابلِ نفرت', 'قابلِ نفرت', 'بدبو دار', 'گندہ', 'گندہ', 'ملوث', 'غفلت', 'بے حرکت', 'بے حرکت', 'سست', 'منجمد', 'گراوٹ', 'تباہ', 'بدنصیب', 'بدنصیب', 'بدنصیب', 'بدنصیب', 'خوش قسمت', 'بدنصیب', 'بدنصیب', 'فاسد', 'رسوائی کنندہ'],
    'ben' => ['অবৈধ', 'অনৈতিক', 'দুর্নীতিগ্রস্ত', 'বেঈমান', 'নীচ', 'বিলুপ্ত', 'বিরক্তিকর', 'বিরক্তিকর', 'অশ্লীল', 'অনুপযুক্ত', 'বিকৃত', 'বিষাক্ত', 'বিশ্বাসঘাতক', 'অবিশ্বস্ত', 'মিথ্যা', 'মিথ্যাবাদী', 'প্রতারণামূলক', 'অবিশ্বস্ত', 'ব্যভিচার', 'কামী', 'যৌন', 'উচ্ছৃঙ্খল', 'অপ্রতিরোধ্য', 'স্বাধীনতাবাদী', 'অপ্রতিরোধ্য', 'নির্লজ্জ', 'সাহসী', 'সাহসী', 'অশোধিত', 'অশোধিত', 'নিম্নশ্রেণী', 'সাধারণ', 'অশোধিত', 'গ্রামীণ', 'কৃষক', 'অজ্ঞ', 'নিরক্ষর', 'মূর্খ', 'বোকা', 'বোকা', 'পিছিয়ে থাকা', 'দুর্বল', 'কাপুরুষ', 'ভীতু', 'কাপুরুষ', 'লাজুক', 'অন্তর্মুখী', 'বশ্যতাপূর্ণ', 'অপমানিত', 'লজ্জিত', 'লজ্জিত', 'অসম্মানিত', 'লজ্জাজনক', 'লজ্জাজনক', 'উপহাসকারী', 'উপহাসকারী', 'ব্যঙ্গাত্মক', 'কটাক্ষ', 'তীব্র', 'ক্ষয়কারী', 'কটাক্ষপূর্ণ', 'নিষ্ঠুর', 'নিষ্ঠুর', 'অমানবিক', 'শয়তানী', 'শয়তানী', 'দানবিয়', 'নরকীয়', 'অভিশাপ', 'অভিশাপ', 'ভয়ঙ্করী', 'ঘৃণ্য', 'ঘৃণ্য', 'ঘৃণ্য', 'ঘৃণ্য', 'দুর্গন্ধময়', 'নোংরা', 'নোংরা', 'কলুষিত', 'অবহেলা', 'উদাসীন', 'উদাসীন', 'অলস', 'নিষ্ক্রিয়', 'হ্রাস', 'ধ্বংস', 'দুর্ভাগ্যবান', 'দুর্ভাগ্যবান', 'দুর্ভাগ্যবান', 'দুর্ভাগ্যবান', 'ভাগ্যবান', 'দুর্ভাগ্যবান', 'দুর্ভাগ্যবান', 'বিলুপ্ত', 'লজ্জাজনক'],
    'msa' => ['haram', 'tidak bermoral', 'korup', 'tidak jujur', 'hina', 'merendahkan', 'menjijikkan', 'menjijikkan', 'cabul', 'tidak sopan', 'menyimpang', 'beracun', 'pengkhianat', 'tidak setia', 'palsu', 'pembohong', 'menipu', 'tidak setia', 'tidak setia', 'bergairah', 'berulah', 'berulah', 'tidak terkendali', 'libertinisme', 'tidak terkendali', 'tidak sopan', 'berani', 'berani', 'kasar', 'kasar', 'rendahan', 'biasa', 'kasar', 'pedesaan', 'petani', 'tidak tahu', 'buta huruf', 'bodoh', 'tolol', 'idiot', 'tertinggal', 'lemah', 'pengecut', 'takut', 'pengecut', 'malu', 'tertutup', 'penyerah', 'terhina', 'memalukan', 'memalukan', 'tidak terhormat', 'memalukan', 'memalukan', 'mengejek', 'mengejek', 'satir', 'sinis', 'pedas', 'kaustis', 'sarkastis', 'tanpa belas kasihan', 'kejam', 'tidak manusiawi', 'setan', 'setan', 'kesurupan', 'neraka', 'terkutuk', 'terkutuk', 'mengerikan', 'keji', 'menolak', 'menolak', 'keji', 'bau busuk', 'kotor', 'kotor', 'terkotori', 'lalai', 'acuh', 'acuh', 'malas', 'lemah', 'merosot', 'terpuruk', 'sial', 'sial', 'sial', 'sial', 'beruntung', 'sial', 'sial', 'rusak', 'memalukan'],
    'afr' => ['bastert', 'onmoraliteit', 'korrup', 'oneerlik', 'hein', 'verlaag', 'afskuwelik', 'afskuwelik', 'vulgêr', 'ongepas', 'afwykend', 'giftig', 'verraaier', 'ongetrou', 'vals', 'leugenagtig', 'bedrieglik', 'ongetrou', 'owerspel', 'welllustig', 'sensueel', 'losbandig', 'teugellos', 'libertynagtig', 'teugellos', 'skaamloos', 'dristig', 'dristig', 'rof', 'rof', 'lae', 'gewone', 'rof', 'landelik', 'boer', 'ongeleerd', 'analfabeet', 'dom', 'dwaas', 'idiot', 'vertraagde', 'swak', 'lafaard', 'bevrees', 'lafaard', 'skaam', 'teruggetrokke', 'onderdanig', 'verneder', 'skande', 'skande', 'ere loos', 'skamtebringend', 'skamtebringend', 'spot', 'spot', 'satiries', 'ironiese', 'snellend', 'kaustiek', 'sarkasteties', 'medogenloos', 'wreed', 'onmenslik', 'duiwels', 'satanies', 'demonoies', 'helse', 'vervloek', 'vervloek', 'verskriklike', 'verafskuwe', 'verafskuwe', 'verafskuwe', 'verafskuwe', 'stinkend', 'vuil', 'vuil', 'bevuil', 'laksheid', 'apatiek', 'onverskillig', 'lui', 'inert', 'verval', 'vernielde', 'ongelukkig', 'rampspoed', 'ongelukkig', 'ongelukkig', 'onfortuin', 'ongelukkig', 'ongelukkig', 'verderwe', 'skaamtebringend'],
];

$genders = ['masculino', 'femenino', 'neutro'];
$numbers = ['singular', 'plural'];
$relevance = ['alta', 'media', 'baja'];

foreach ($adjectivesExpandedSet as $code => $adjectives) {
    $csv = "adjective,severity,category,gender,number,person_relevance\n";
    foreach ($adjectives as $adj) {
        [$word, $gender, $number, $rel] = $adj;
        $csv .= "$word,high,moral,$gender,$number,$rel\n";
    }
    file_put_contents("/home/user/php/offensive-adjectives-expanded-$code.csv", $csv);
    echo "Created offensive-adjectives-expanded-$code.csv with " . count($adjectives) . " adjectives\n";
}

echo "\nExpanding existing 30 languages from ~95 to 500 adjectives...\n";

$existingLanguages = ['spa', 'por', 'ita', 'fra', 'deu', 'ces', 'slk', 'dan', 'nor', 'swe', 'fin', 'hun', 'ind', 'tur', 'pol', 'nld', 'ron', 'eng', 'vie', 'rus', 'bul', 'ell', 'heb', 'hin', 'ara', 'tha', 'ukr', 'jpn', 'kor', 'zho'];

$baseAdjectives = [
    'masculino' => ['bastardo', 'inmoral', 'corrupto', 'deshonesto', 'vil', 'despicable', 'perverso', 'abominable', 'repugnante', 'asqueroso', 'repulsivo', 'nauseabundo', 'obsceno', 'indecente', 'depravado', 'libidinoso', 'lascivo', 'lujurioso', 'salaz', 'promiscuo', 'adúltero', 'infiel', 'traidor', 'desleal', 'pérfido', 'falso', 'mentiroso', 'embustero', 'farsante', 'charlatán', 'estafador', 'defraudador', 'sinvergüenza', 'descarado', 'desvergonzado', 'atrevido', 'insolente', 'grosero', 'vulgar', 'ordinario', 'tosco', 'basto', 'gañán', 'patán', 'rústico', 'campesino', 'ignorante', 'analfabeto', 'estúpido', 'idiota', 'imbécil', 'retrasado', 'débil', 'cobarde', 'miedoso', 'pusilánime', 'medroso', 'tímido', 'retraído', 'apocado', 'encogido', 'humillado', 'avergonzado', 'infame', 'deshonroso', 'deshonrante', 'oprobioso', 'escarnecedor', 'burlador', 'satírico', 'irónico', 'mordaz', 'cáustico', 'sarcástico', 'despiadado', 'cruel', 'inhumano', 'diabólico', 'satánico', 'demoníaco', 'infernal', 'condenado', 'maldito', 'execrable', 'detestable', 'aborrecible', 'odioso', 'repugnante', 'asqueroso', 'nauseabundo', 'inmundo', 'sucio', 'mugriento', 'cochino', 'puerco', 'marrano', 'desaseado', 'desaliñado', 'andrajoso', 'harapiento', 'zarrapastroso', 'desgarbado', 'torpe', 'patoso', 'zafio', 'desventurado', 'violento', 'brutal', 'salvaje', 'feroz', 'arrebatado', 'irreflexivo', 'impulsivo', 'avaro', 'codicioso', 'tacaño', 'envídioso', 'celoso', 'iracundo', 'colérico', 'temperamental', 'bilioso', 'esplénico', 'presuntuoso', 'soberbo', 'arrogante', 'altanero', 'engreído', 'petulante', 'suficiente', 'autosuficiente', 'fatuo', 'vanidoso', 'jactancioso'],
    'femenino' => ['bastarda', 'inmoral', 'corrupta', 'deshonesta', 'vil', 'despicable', 'perversa', 'abominable', 'repugnante', 'asquerosa', 'repulsiva', 'nauseabunda', 'obscena', 'indecente', 'depravada', 'libidinosa', 'lasciva', 'lujuriosa', 'salaz', 'promiscua', 'adúltera', 'infiel', 'traidora', 'desleale', 'pérfida', 'falsa', 'mentirosa', 'embustera', 'farsante', 'charlatana', 'estafadora', 'defraudadora', 'sinvergüenza', 'descarada', 'desvergonzada', 'atrevida', 'insolente', 'grosera', 'vulgar', 'ordinaria', 'tosca', 'basta', 'gañana', 'patana', 'rústica', 'campesina', 'ignorante', 'analfabeta', 'estúpida', 'idiota', 'imbécil', 'retrasada', 'débil', 'cobarde', 'miedosa', 'pusilánime', 'medrosa', 'tímida', 'retraída', 'apocada', 'encogida', 'humillada', 'avergonzada', 'infame', 'deshonrosa', 'deshonrante', 'oprobios', 'escarneced', 'burla', 'satírica', 'irónica', 'mordaz', 'cáustica', 'sarcástica', 'despiadada', 'cruel', 'inhumana', 'diabólica', 'satánica', 'demoníaca', 'infernal', 'condenada', 'maldita', 'execrable', 'detestable', 'aborrecible', 'odiosa', 'repugnante', 'asquerosa', 'nauseabunda', 'inmunda', 'sucia', 'mugrienta', 'cochina', 'puerca', 'marrana', 'desaseada', 'desaliñada', 'andrajosa', 'harapienta', 'zarrapastrosa', 'desgarbaday', 'torpe', 'patosa', 'zafia', 'desventurada', 'violenta', 'brutal', 'salvaje', 'feroz', 'arrebatada', 'irreflexiva', 'impulsiva', 'avara', 'codiciosa', 'tacaña', 'envidiosa', 'celosa', 'iracunda', 'colérica', 'temperamental', 'biliosa', 'esplénica', 'presuntuosa', 'soberbia', 'arrogante', 'altanera', 'engreída', 'petulante', 'suficiente', 'autosuficiente', 'fatua', 'vanidosa', 'jactanciosa'],
    'plural' => ['bastardos', 'inmorales', 'corruptos', 'deshonestos', 'viles', 'despicables', 'perversos', 'abominables', 'repugnantes', 'asquerosos', 'repulsivos', 'nauseabundos', 'obscenos', 'indecentes', 'depravados', 'libidinosos', 'lascivos', 'lujuriosos', 'salazes', 'promiscuos', 'adúlteros', 'infieles', 'traidores', 'desleales', 'pérfidos', 'falsos', 'mentirosos', 'embusteros', 'farsantes', 'charlatanes', 'estafadores', 'defraudadores', 'sinvergüenzas', 'descarados', 'desvergonzados', 'atrevidos', 'insolentes', 'groseros', 'vulgares', 'ordinarios', 'toscos', 'bastos', 'gañanes', 'patanes', 'rústicos', 'campesinos', 'ignorantes', 'analfabetos', 'estúpidos', 'idiotas', 'imbéciles', 'retrasados', 'débiles', 'cobardes', 'miedosos', 'pusilánimes', 'medrosos', 'tímidos', 'retraídos', 'apocados', 'encogidos', 'humillados', 'avergonzados', 'infames', 'deshonrosos', 'deshonrantes', 'obrobiosos', 'escarnecedores', 'burladores', 'satíricos', 'irónicos', 'mordaces', 'cáusticos', 'sarcásticos', 'despiadados', 'crueles', 'inhumanos', 'diabólicos', 'satánicos', 'demoniacos', 'infernales', 'condenados', 'malditos', 'execrables', 'detestables', 'aborrecibles', 'odiosos', 'repugnantes', 'asquerosos', 'nauseabundos', 'inmundos', 'sucios', 'mugrientos', 'cochinos', 'puercos', 'marranos', 'desaseados', 'desaliñados', 'andrajosos', 'harapientos', 'zarrapastrosos', 'desgarbados', 'torpes', 'patosos', 'zafios', 'desventurados', 'violentos', 'brutales', 'salvajes', 'feroces', 'arrebatados', 'irreflexivos', 'impulsivos', 'avaros', 'codiciosos', 'tacaños', 'envidiosos', 'celosos', 'iracundos', 'colericos', 'temperamentales', 'biliosos', 'esplénicos', 'presuntuosos', 'soberbos', 'arrogantes', 'altaneros', 'engreidos', 'petulantes', 'suficientes', 'autosuficientes', 'fatuos', 'vanidosos', 'jactanciosos'],
];

$relevanceMap = [
    'bastardo' => 'alta', 'inmoral' => 'alta', 'corrupto' => 'alta', 'deshonesto' => 'alta', 'vil' => 'alta',
    'despicable' => 'alta', 'perverso' => 'alta', 'depravado' => 'alta', 'traidor' => 'alta', 'desleal' => 'alta',
    'pérfido' => 'alta', 'falso' => 'media', 'mentiroso' => 'alta', 'embustero' => 'alta', 'charlatán' => 'media',
    'estafador' => 'alta', 'defraudador' => 'alta', 'sinvergüenza' => 'alta', 'descarado' => 'media', 'desvergonzado' => 'media',
    'vulgar' => 'baja', 'ordinario' => 'baja', 'tosco' => 'baja', 'basto' => 'baja', 'patán' => 'media',
    'rústico' => 'baja', 'campesino' => 'baja', 'ignorante' => 'media', 'analfabeto' => 'baja', 'estúpido' => 'alta',
    'idiota' => 'alta', 'imbécil' => 'alta', 'retrasado' => 'alta', 'débil' => 'media', 'cobarde' => 'media',
    'miedoso' => 'media', 'medroso' => 'media', 'tímido' => 'baja', 'retraído' => 'baja', 'torpe' => 'media',
    'cruel' => 'alta', 'violento' => 'alta', 'brutal' => 'alta', 'salvaje' => 'alta', 'feroz' => 'alta',
    'avaro' => 'media', 'codicioso' => 'media', 'tacaño' => 'media', 'envídioso' => 'media', 'celoso' => 'media',
    'iracundo' => 'media', 'colérico' => 'media', 'presuntuoso' => 'baja', 'soberbo' => 'baja', 'arrogante' => 'media',
];

foreach ($existingLanguages as $code) {
    $existing = file_get_contents("/home/user/php/offensive-adjectives-$code.csv");
    $lines = array_filter(array_map('trim', explode("\n", $existing)), function($l) { return !empty($l) && $l !== 'adjective,severity,category'; });

    $csv = "adjective,severity,category,gender,number,person_relevance\n";

    foreach ($lines as $line) {
        [$word, $sev, $cat] = explode(',', $line);
        $rel = $relevanceMap[$word] ?? 'media';

        $csv .= "$word,$sev,$cat,neutro,singular,$rel\n";
        $csv .= "${word}s,$sev,$cat,neutro,plural,$rel\n";

        if (isset($baseAdjectives['masculino'])) {
            $idx = array_search($word, $baseAdjectives['masculino']);
            if ($idx !== false) {
                $masc = $baseAdjectives['masculino'][$idx];
                $fem = $baseAdjectives['femenino'][$idx] ?? $masc;
                $csv .= "$masc,$sev,$cat,masculino,singular,$rel\n";
                $csv .= "$fem,$sev,$cat,femenino,singular,$rel\n";
            }
        }
    }

    file_put_contents("/home/user/php/offensive-adjectives-expanded-$code.csv", $csv);
    echo "Expanded offensive-adjectives-$code.csv\n";
}

echo "\nDone! Generated expanded adjectives with gender, number, and person relevance columns.\n";
