<?php

$adjectivesExpandedSet = [
    'fas' => [
        ['بدجنس', 'masculino', 'singular', 'alta'],
        ['بیاخلاق', 'neutro', 'singular', 'media'],
        ['فاسد', 'masculino', 'singular', 'alta'],
        ['بددل', 'masculino', 'singular', 'alta'],
        ['ذلیل', 'masculino', 'singular', 'alta'],
        ['شهوتران', 'masculino', 'singular', 'media'],
        ['متنفراننده', 'neutro', 'singular', 'baja'],
        ['فحش', 'masculino', 'singular', 'media'],
        ['نامناسب', 'neutro', 'singular', 'media'],
        ['منحرف', 'masculino', 'singular', 'alta'],
        ['سمی', 'masculino', 'singular', 'baja'],
        ['خیانتکار', 'masculino', 'singular', 'alta'],
        ['بدرفتار', 'masculino', 'singular', 'alta'],
        ['دروغ', 'masculino', 'singular', 'media'],
        ['دروغ گو', 'masculino', 'singular', 'alta'],
        ['فریب دهنده', 'masculino', 'singular', 'alta'],
        ['زنا', 'masculino', 'singular', 'media'],
        ['شهوانی', 'masculino', 'singular', 'media'],
        ['جنسی', 'masculino', 'singular', 'media'],
        ['رفتار بی شرمانه', 'masculino', 'singular', 'media'],
        ['بی قید', 'neutro', 'singular', 'media'],
        ['آزادی خواه', 'masculino', 'singular', 'media'],
        ['بی شرم', 'masculino', 'singular', 'media'],
        ['جسور', 'masculino', 'singular', 'baja'],
        ['شجاع', 'masculino', 'singular', 'baja'],
        ['خشن', 'masculino', 'singular', 'media'],
        ['نامناسب', 'neutro', 'singular', 'baja'],
        ['عام', 'neutro', 'singular', 'baja'],
        ['روستایی', 'masculino', 'singular', 'baja'],
        ['دهقان', 'masculino', 'singular', 'baja'],
        ['نادان', 'masculino', 'singular', 'media'],
        ['بی سوادی', 'masculino', 'singular', 'baja'],
        ['احمق', 'masculino', 'singular', 'alta'],
        ['تاخیر', 'masculino', 'singular', 'alta'],
        ['ضعیف', 'masculino', 'singular', 'media'],
        ['بزدل', 'masculino', 'singular', 'media'],
        ['ترسو', 'masculino', 'singular', 'media'],
        ['شرم و حیا', 'masculino', 'singular', 'baja'],
        ['بسته', 'masculino', 'singular', 'baja'],
        ['تابع', 'masculino', 'singular', 'baja'],
        ['تحقیر شده', 'masculino', 'singular', 'media'],
        ['شرمنده', 'masculino', 'singular', 'media'],
        ['بی نام و نشان', 'masculino', 'singular', 'media'],
        ['رسوا کننده', 'masculino', 'singular', 'media'],
        ['مسخره', 'masculino', 'singular', 'baja'],
        ['طنز آمیز', 'masculino', 'singular', 'baja'],
        ['ایرونیک', 'masculino', 'singular', 'baja'],
        ['تیز تراش', 'masculino', 'singular', 'baja'],
        ['خورنده', 'masculino', 'singular', 'baja'],
        ['طنز آمیز', 'masculino', 'singular', 'baja'],
        ['بی رحم', 'masculino', 'singular', 'media'],
        ['قاسی', 'masculino', 'singular', 'alta'],
        ['غیرانسانی', 'masculino', 'singular', 'alta'],
        ['ابلیسی', 'masculino', 'singular', 'alta'],
        ['شیطانی', 'masculino', 'singular', 'alta'],
        ['ابلیسی', 'masculino', 'singular', 'alta'],
        ['جهنمی', 'masculino', 'singular', 'alta'],
        ['لعنتی', 'masculino', 'singular', 'media'],
        ['وحشتناک', 'masculino', 'singular', 'alta'],
        ['نفرت انگیز', 'masculino', 'singular', 'media'],
        ['بدبو', 'masculino', 'singular', 'baja'],
        ['کثیف', 'masculino', 'singular', 'baja'],
        ['آلوده', 'masculino', 'singular', 'baja'],
        ['غفلت', 'masculino', 'singular', 'baja'],
        ['بی تفاوت', 'masculino', 'singular', 'media'],
        ['تنبل', 'masculino', 'singular', 'media'],
        ['بی جان', 'masculino', 'singular', 'baja'],
        ['کاهش', 'masculino', 'singular', 'baja'],
        ['تخریب', 'masculino', 'singular', 'baja'],
        ['بدبخت', 'masculino', 'singular', 'media'],
        ['بدشانس', 'masculino', 'singular', 'media'],
        ['فاسد', 'masculino', 'singular', 'alta'],
        ['رسوا کننده', 'masculino', 'singular', 'media'],
        ['سفاک', 'masculino', 'singular', 'alta'],
        ['پلید', 'masculino', 'singular', 'baja'],
        ['ناپاک', 'masculino', 'singular', 'baja'],
        ['ناشایست', 'masculino', 'singular', 'media'],
        ['ناشناس', 'masculino', 'singular', 'baja'],
        ['رقیق', 'masculino', 'singular', 'baja'],
        ['نامعروف', 'masculino', 'singular', 'baja'],
        ['ناتوان', 'masculino', 'singular', 'media'],
        ['غیرقابل اعتماد', 'masculino', 'singular', 'alta'],
        ['متلاشی', 'masculino', 'singular', 'baja'],
        ['واهی', 'masculino', 'singular', 'baja'],
        ['ضعیف الاساس', 'masculino', 'singular', 'baja'],
        ['غیرمؤثر', 'masculino', 'singular', 'baja'],
        ['کم بنیاد', 'masculino', 'singular', 'baja'],
        ['خودپسند', 'masculino', 'singular', 'baja'],
        ['متکبر', 'masculino', 'singular', 'media'],
        ['غرور آمیز', 'masculino', 'singular', 'baja'],
        ['خودرائی', 'masculino', 'singular', 'media'],
        ['خودستایی کننده', 'masculino', 'singular', 'baja'],
    ],
    'urd' => [
        ['غیر شریف', 'masculino', 'singular', 'alta'],
        ['بے اخلاق', 'masculino', 'singular', 'alta'],
        ['بدعنوان', 'masculino', 'singular', 'alta'],
        ['بے ایمان', 'masculino', 'singular', 'alta'],
        ['ذلیل', 'masculino', 'singular', 'alta'],
        ['کمینہ', 'masculino', 'singular', 'alta'],
        ['ناپسندیدہ', 'masculino', 'singular', 'baja'],
        ['فحش', 'masculino', 'singular', 'media'],
        ['نامناسب', 'neutro', 'singular', 'media'],
        ['منحرف', 'masculino', 'singular', 'alta'],
        ['زہریلا', 'masculino', 'singular', 'baja'],
        ['غدار', 'masculino', 'singular', 'alta'],
        ['بے وفا', 'masculino', 'singular', 'alta'],
        ['جھوٹا', 'masculino', 'singular', 'media'],
        ['جھوٹا', 'masculino', 'singular', 'alta'],
        ['فریب دہندہ', 'masculino', 'singular', 'alta'],
        ['زنا', 'masculino', 'singular', 'media'],
        ['شہوانی', 'masculino', 'singular', 'media'],
        ['جنسی', 'masculino', 'singular', 'media'],
        ['لواہام', 'masculino', 'singular', 'media'],
        ['بے لگام', 'neutro', 'singular', 'media'],
        ['آزادی خواہ', 'masculino', 'singular', 'media'],
        ['بے شرم', 'masculino', 'singular', 'media'],
        ['جرات مندانہ', 'masculino', 'singular', 'baja'],
        ['بہادرانہ', 'masculino', 'singular', 'baja'],
        ['خشن', 'masculino', 'singular', 'media'],
        ['نامناسب', 'neutro', 'singular', 'baja'],
        ['عام', 'neutro', 'singular', 'baja'],
        ['دیہاتی', 'masculino', 'singular', 'baja'],
        ['کسان', 'masculino', 'singular', 'baja'],
        ['نادان', 'masculino', 'singular', 'media'],
        ['ان پڑھ', 'masculino', 'singular', 'baja'],
        ['احمق', 'masculino', 'singular', 'alta'],
        ['تاخیر', 'masculino', 'singular', 'alta'],
        ['کمزور', 'masculino', 'singular', 'media'],
        ['بزدل', 'masculino', 'singular', 'media'],
        ['ڈرپوک', 'masculino', 'singular', 'media'],
        ['شرم و حیا', 'masculino', 'singular', 'baja'],
        ['بند', 'masculino', 'singular', 'baja'],
        ['تابع', 'masculino', 'singular', 'baja'],
        ['ذلیل', 'masculino', 'singular', 'media'],
        ['شرمندہ', 'masculino', 'singular', 'media'],
        ['ناپاک', 'masculino', 'singular', 'media'],
        ['رسوائی کنندہ', 'masculino', 'singular', 'media'],
        ['مسخرہ', 'masculino', 'singular', 'baja'],
        ['طنز آمیز', 'masculino', 'singular', 'baja'],
        ['تھکا ہوا', 'masculino', 'singular', 'baja'],
        ['تیز', 'masculino', 'singular', 'baja'],
        ['کاٹنے والا', 'masculino', 'singular', 'baja'],
        ['طنز آمیز', 'masculino', 'singular', 'baja'],
        ['بے رحم', 'masculino', 'singular', 'media'],
        ['ظالم', 'masculino', 'singular', 'alta'],
        ['غیر انسانی', 'masculino', 'singular', 'alta'],
        ['شیطانی', 'masculino', 'singular', 'alta'],
        ['شیطانی', 'masculino', 'singular', 'alta'],
        ['شیطانی', 'masculino', 'singular', 'alta'],
        ['جہنمی', 'masculino', 'singular', 'alta'],
        ['ملعون', 'masculino', 'singular', 'media'],
        ['ہولناک', 'masculino', 'singular', 'alta'],
        ['قابلِ نفرت', 'masculino', 'singular', 'media'],
        ['بدبو دار', 'masculino', 'singular', 'baja'],
        ['گندہ', 'masculino', 'singular', 'baja'],
        ['ملوث', 'masculino', 'singular', 'baja'],
        ['غفلت', 'masculino', 'singular', 'baja'],
        ['بے حرکت', 'masculino', 'singular', 'media'],
        ['سست', 'masculino', 'singular', 'media'],
        ['منجمد', 'masculino', 'singular', 'baja'],
        ['گراوٹ', 'masculino', 'singular', 'baja'],
        ['تباہ', 'masculino', 'singular', 'baja'],
        ['بدنصیب', 'masculino', 'singular', 'media'],
        ['خوش قسمت', 'masculino', 'singular', 'media'],
        ['رسوائی کنندہ', 'masculino', 'singular', 'media'],
        ['مہکنے والا', 'masculino', 'singular', 'baja'],
        ['گندگی', 'masculino', 'singular', 'baja'],
        ['ناپاکی', 'masculino', 'singular', 'baja'],
        ['نا پاک', 'masculino', 'singular', 'baja'],
        ['بے خیالی', 'masculino', 'singular', 'baja'],
        ['سست رفتار', 'masculino', 'singular', 'media'],
        ['سست ذہن', 'masculino', 'singular', 'alta'],
        ['گھٹیا', 'masculino', 'singular', 'media'],
        ['کم تر', 'masculino', 'singular', 'baja'],
        ['کم سے کم', 'masculino', 'singular', 'baja'],
        ['کم ترین', 'masculino', 'singular', 'baja'],
        ['سب سے کم', 'masculino', 'singular', 'baja'],
        ['سب سے گھٹیا', 'masculino', 'singular', 'alta'],
        ['حقیر', 'masculino', 'singular', 'alta'],
        ['تحقیر آمیز', 'masculino', 'singular', 'media'],
    ],
    'ben' => [
        ['অবৈধ', 'masculino', 'singular', 'alta'],
        ['অনৈতিক', 'masculino', 'singular', 'alta'],
        ['দুর্নীতিগ্রস্ত', 'masculino', 'singular', 'alta'],
        ['বেঈমান', 'masculino', 'singular', 'alta'],
        ['নীচ', 'masculino', 'singular', 'alta'],
        ['বিলুপ্ত', 'masculino', 'singular', 'alta'],
        ['বিরক্তিকর', 'masculino', 'singular', 'baja'],
        ['অশ্লীল', 'masculino', 'singular', 'media'],
        ['অনুপযুক্ত', 'neutro', 'singular', 'media'],
        ['বিকৃত', 'masculino', 'singular', 'alta'],
        ['বিষাক্ত', 'masculino', 'singular', 'baja'],
        ['বিশ্বাসঘাতক', 'masculino', 'singular', 'alta'],
        ['অবিশ্বস্ত', 'masculino', 'singular', 'alta'],
        ['মিথ্যা', 'masculino', 'singular', 'media'],
        ['মিথ্যাবাদী', 'masculino', 'singular', 'alta'],
        ['প্রতারণামূলক', 'masculino', 'singular', 'alta'],
        ['ব্যভিচার', 'masculino', 'singular', 'media'],
        ['কামী', 'masculino', 'singular', 'media'],
        ['যৌন', 'masculino', 'singular', 'media'],
        ['উচ্ছৃঙ্খল', 'masculino', 'singular', 'media'],
        ['অপ্রতিরোধ্য', 'neutro', 'singular', 'media'],
        ['স্বাধীনতাবাদী', 'masculino', 'singular', 'media'],
        ['নির্লজ্জ', 'masculino', 'singular', 'media'],
        ['সাহসী', 'masculino', 'singular', 'baja'],
        ['সাহসী', 'masculino', 'singular', 'baja'],
        ['অশোধিত', 'masculino', 'singular', 'media'],
        ['অনুপযুক্ত', 'neutro', 'singular', 'baja'],
        ['সাধারণ', 'neutro', 'singular', 'baja'],
        ['গ্রামীণ', 'masculino', 'singular', 'baja'],
        ['কৃষক', 'masculino', 'singular', 'baja'],
        ['অজ্ঞ', 'masculino', 'singular', 'media'],
        ['নিরক্ষর', 'masculino', 'singular', 'baja'],
        ['মূর্খ', 'masculino', 'singular', 'alta'],
        ['পিছিয়ে থাকা', 'masculino', 'singular', 'alta'],
        ['দুর্বল', 'masculino', 'singular', 'media'],
        ['কাপুরুষ', 'masculino', 'singular', 'media'],
        ['ভীতু', 'masculino', 'singular', 'media'],
        ['লাজুক', 'masculino', 'singular', 'baja'],
        ['অন্তর্মুখী', 'masculino', 'singular', 'baja'],
        ['বশ্যতাপূর্ণ', 'masculino', 'singular', 'baja'],
        ['অপমানিত', 'masculino', 'singular', 'media'],
        ['লজ্জিত', 'masculino', 'singular', 'media'],
        ['অসম্মানিত', 'masculino', 'singular', 'media'],
        ['লজ্জাজনক', 'masculino', 'singular', 'media'],
        ['উপহাসকারী', 'masculino', 'singular', 'baja'],
        ['ব্যঙ্গাত্মক', 'masculino', 'singular', 'baja'],
        ['কটাক্ষ', 'masculino', 'singular', 'baja'],
        ['তীব্র', 'masculino', 'singular', 'baja'],
        ['ক্ষয়কারী', 'masculino', 'singular', 'baja'],
        ['কটাক্ষপূর্ণ', 'masculino', 'singular', 'baja'],
        ['নিষ্ঠুর', 'masculino', 'singular', 'media'],
        ['অমানবিক', 'masculino', 'singular', 'alta'],
        ['শয়তানী', 'masculino', 'singular', 'alta'],
        ['দানবিয়', 'masculino', 'singular', 'alta'],
        ['নরকীয়', 'masculino', 'singular', 'alta'],
        ['অভিশাপ', 'masculino', 'singular', 'media'],
        ['ভয়ঙ্করী', 'masculino', 'singular', 'alta'],
        ['ঘৃণ্য', 'masculino', 'singular', 'media'],
        ['দুর্গন্ধময়', 'masculino', 'singular', 'baja'],
        ['নোংরা', 'masculino', 'singular', 'baja'],
        ['কলুষিত', 'masculino', 'singular', 'baja'],
        ['অবহেলা', 'masculino', 'singular', 'baja'],
        ['উদাসীন', 'masculino', 'singular', 'media'],
        ['অলস', 'masculino', 'singular', 'media'],
        ['নিষ্ক্রিয়', 'masculino', 'singular', 'baja'],
        ['হ্রাস', 'masculino', 'singular', 'baja'],
        ['ধ্বংস', 'masculino', 'singular', 'baja'],
        ['দুর্ভাগ্যবান', 'masculino', 'singular', 'media'],
        ['ভাগ্যবান', 'masculino', 'singular', 'media'],
        ['মন্দ', 'masculino', 'singular', 'alta'],
        ['খারাপ', 'masculino', 'singular', 'alta'],
        ['নিকৃষ্ট', 'masculino', 'singular', 'alta'],
        ['তুচ্ছ', 'masculino', 'singular', 'baja'],
        ['সাধারণ', 'neutro', 'singular', 'baja'],
        ['নিম্নমানের', 'masculino', 'singular', 'baja'],
        ['নিম্ন', 'masculino', 'singular', 'baja'],
        ['অবনত', 'masculino', 'singular', 'baja'],
        ['বিলুপ্ত', 'masculino', 'singular', 'alta'],
        ['লজ্জাজনক', 'masculino', 'singular', 'media'],
    ],
    'msa' => [
        ['haram', 'masculino', 'singular', 'alta'],
        ['tidak bermoral', 'masculino', 'singular', 'alta'],
        ['korup', 'masculino', 'singular', 'alta'],
        ['tidak jujur', 'masculino', 'singular', 'alta'],
        ['hina', 'masculino', 'singular', 'alta'],
        ['merendahkan', 'masculino', 'singular', 'alta'],
        ['menjijikkan', 'masculino', 'singular', 'baja'],
        ['cabul', 'masculino', 'singular', 'media'],
        ['tidak sopan', 'neutro', 'singular', 'media'],
        ['menyimpang', 'masculino', 'singular', 'alta'],
        ['beracun', 'masculino', 'singular', 'baja'],
        ['pengkhianat', 'masculino', 'singular', 'alta'],
        ['tidak setia', 'masculino', 'singular', 'alta'],
        ['palsu', 'masculino', 'singular', 'media'],
        ['pembohong', 'masculino', 'singular', 'alta'],
        ['menipu', 'masculino', 'singular', 'alta'],
        ['tidak setia', 'masculino', 'singular', 'media'],
        ['bergairah', 'masculino', 'singular', 'media'],
        ['berulah', 'masculino', 'singular', 'media'],
        ['tidak terkendali', 'neutro', 'singular', 'media'],
        ['libertinisme', 'masculino', 'singular', 'media'],
        ['tidak terkendali', 'masculino', 'singular', 'media'],
        ['tidak sopan', 'masculino', 'singular', 'media'],
        ['berani', 'masculino', 'singular', 'baja'],
        ['berani', 'masculino', 'singular', 'baja'],
        ['kasar', 'masculino', 'singular', 'media'],
        ['tidak sopan', 'neutro', 'singular', 'baja'],
        ['biasa', 'neutro', 'singular', 'baja'],
        ['pedesaan', 'masculino', 'singular', 'baja'],
        ['petani', 'masculino', 'singular', 'baja'],
        ['tidak tahu', 'masculino', 'singular', 'media'],
        ['buta huruf', 'masculino', 'singular', 'baja'],
        ['bodoh', 'masculino', 'singular', 'alta'],
        ['tertinggal', 'masculino', 'singular', 'alta'],
        ['lemah', 'masculino', 'singular', 'media'],
        ['pengecut', 'masculino', 'singular', 'media'],
        ['takut', 'masculino', 'singular', 'media'],
        ['malu', 'masculino', 'singular', 'baja'],
        ['tertutup', 'masculino', 'singular', 'baja'],
        ['penyerah', 'masculino', 'singular', 'baja'],
        ['terhina', 'masculino', 'singular', 'media'],
        ['memalukan', 'masculino', 'singular', 'media'],
        ['tidak terhormat', 'masculino', 'singular', 'media'],
        ['memalukan', 'masculino', 'singular', 'media'],
        ['mengejek', 'masculino', 'singular', 'baja'],
        ['satir', 'masculino', 'singular', 'baja'],
        ['sinis', 'masculino', 'singular', 'baja'],
        ['pedas', 'masculino', 'singular', 'baja'],
        ['kaustis', 'masculino', 'singular', 'baja'],
        ['sarkastis', 'masculino', 'singular', 'baja'],
        ['tanpa belas kasihan', 'masculino', 'singular', 'media'],
        ['kejam', 'masculino', 'singular', 'alta'],
        ['tidak manusiawi', 'masculino', 'singular', 'alta'],
        ['setan', 'masculino', 'singular', 'alta'],
        ['kesurupan', 'masculino', 'singular', 'alta'],
        ['neraka', 'masculino', 'singular', 'alta'],
        ['terkutuk', 'masculino', 'singular', 'media'],
        ['mengerikan', 'masculino', 'singular', 'alta'],
        ['keji', 'masculino', 'singular', 'media'],
        ['bau busuk', 'masculino', 'singular', 'baja'],
        ['kotor', 'masculino', 'singular', 'baja'],
        ['terkotori', 'masculino', 'singular', 'baja'],
        ['lalai', 'masculino', 'singular', 'baja'],
        ['acuh', 'masculino', 'singular', 'media'],
        ['malas', 'masculino', 'singular', 'media'],
        ['lemah', 'masculino', 'singular', 'baja'],
        ['merosot', 'masculino', 'singular', 'baja'],
        ['terpuruk', 'masculino', 'singular', 'baja'],
        ['sial', 'masculino', 'singular', 'media'],
        ['beruntung', 'masculino', 'singular', 'media'],
        ['rusak', 'masculino', 'singular', 'media'],
        ['memalukan', 'masculino', 'singular', 'media'],
        ['tercela', 'masculino', 'singular', 'alta'],
        ['cemoohan', 'masculino', 'singular', 'baja'],
        ['sinistis', 'masculino', 'singular', 'baja'],
        ['pesimis', 'masculino', 'singular', 'baja'],
        ['negatif', 'masculino', 'singular', 'baja'],
        ['putus asa', 'masculino', 'singular', 'media'],
    ],
    'afr' => [
        ['bastert', 'masculino', 'singular', 'alta'],
        ['onmoraliteit', 'masculino', 'singular', 'alta'],
        ['korrup', 'masculino', 'singular', 'alta'],
        ['oneerlik', 'masculino', 'singular', 'alta'],
        ['hein', 'masculino', 'singular', 'alta'],
        ['verlaag', 'masculino', 'singular', 'alta'],
        ['afskuwelik', 'masculino', 'singular', 'baja'],
        ['vulgêr', 'masculino', 'singular', 'media'],
        ['ongepas', 'neutro', 'singular', 'media'],
        ['afwykend', 'masculino', 'singular', 'alta'],
        ['giftig', 'masculino', 'singular', 'baja'],
        ['verraaier', 'masculino', 'singular', 'alta'],
        ['ongetrou', 'masculino', 'singular', 'alta'],
        ['vals', 'masculino', 'singular', 'media'],
        ['leugenagtig', 'masculino', 'singular', 'alta'],
        ['bedrieglik', 'masculino', 'singular', 'alta'],
        ['owerspel', 'masculino', 'singular', 'media'],
        ['welllustig', 'masculino', 'singular', 'media'],
        ['sensueel', 'masculino', 'singular', 'media'],
        ['losbandig', 'masculino', 'singular', 'media'],
        ['teugellos', 'neutro', 'singular', 'media'],
        ['libertynagtig', 'masculino', 'singular', 'media'],
        ['skaamloos', 'masculino', 'singular', 'media'],
        ['dristig', 'masculino', 'singular', 'baja'],
        ['dristig', 'masculino', 'singular', 'baja'],
        ['rof', 'masculino', 'singular', 'media'],
        ['ongepas', 'neutro', 'singular', 'baja'],
        ['gewone', 'neutro', 'singular', 'baja'],
        ['landelik', 'masculino', 'singular', 'baja'],
        ['boer', 'masculino', 'singular', 'baja'],
        ['ongeleerd', 'masculino', 'singular', 'media'],
        ['analfabeet', 'masculino', 'singular', 'baja'],
        ['dom', 'masculino', 'singular', 'alta'],
        ['vertraagde', 'masculino', 'singular', 'alta'],
        ['swak', 'masculino', 'singular', 'media'],
        ['lafaard', 'masculino', 'singular', 'media'],
        ['bevrees', 'masculino', 'singular', 'media'],
        ['skaam', 'masculino', 'singular', 'baja'],
        ['teruggetrokke', 'masculino', 'singular', 'baja'],
        ['onderdanig', 'masculino', 'singular', 'baja'],
        ['verneder', 'masculino', 'singular', 'media'],
        ['skande', 'masculino', 'singular', 'media'],
        ['ere loos', 'masculino', 'singular', 'media'],
        ['skamtebringend', 'masculino', 'singular', 'media'],
        ['spot', 'masculino', 'singular', 'baja'],
        ['satiries', 'masculino', 'singular', 'baja'],
        ['ironiese', 'masculino', 'singular', 'baja'],
        ['snellend', 'masculino', 'singular', 'baja'],
        ['kaustiek', 'masculino', 'singular', 'baja'],
        ['sarkasteties', 'masculino', 'singular', 'baja'],
        ['medogenloos', 'masculino', 'singular', 'media'],
        ['wreed', 'masculino', 'singular', 'alta'],
        ['onmenslik', 'masculino', 'singular', 'alta'],
        ['duiwels', 'masculino', 'singular', 'alta'],
        ['satanies', 'masculino', 'singular', 'alta'],
        ['demonoies', 'masculino', 'singular', 'alta'],
        ['helse', 'masculino', 'singular', 'alta'],
        ['vervloek', 'masculino', 'singular', 'media'],
        ['verskriklike', 'masculino', 'singular', 'alta'],
        ['verafskuwe', 'masculino', 'singular', 'media'],
        ['stinkend', 'masculino', 'singular', 'baja'],
        ['vuil', 'masculino', 'singular', 'baja'],
        ['bevuil', 'masculino', 'singular', 'baja'],
        ['laksheid', 'masculino', 'singular', 'baja'],
        ['apatiek', 'masculino', 'singular', 'media'],
        ['onverskillig', 'masculino', 'singular', 'media'],
        ['lui', 'masculino', 'singular', 'media'],
        ['inert', 'masculino', 'singular', 'baja'],
        ['verval', 'masculino', 'singular', 'baja'],
        ['vernielde', 'masculino', 'singular', 'baja'],
        ['ongelukkig', 'masculino', 'singular', 'media'],
        ['rampspoed', 'masculino', 'singular', 'media'],
        ['onfortuin', 'masculino', 'singular', 'media'],
        ['skaamtebringend', 'masculino', 'singular', 'media'],
        ['ledermaatend', 'masculino', 'singular', 'baja'],
        ['schandend', 'masculino', 'singular', 'baja'],
        ['beledigend', 'masculino', 'singular', 'baja'],
        ['vernederend', 'masculino', 'singular', 'media'],
    ],
];

foreach ($adjectivesExpandedSet as $code => $adjectives) {
    $csv = "adjective,severity,category,gender,number,person_relevance\n";
    foreach ($adjectives as $adj) {
        [$word, $gender, $number, $rel] = $adj;
        $csv .= "$word,high,moral,$gender,$number,$rel\n";
    }
    file_put_contents("/home/user/php/offensive-adjectives-expanded-$code.csv", $csv);
    echo "Created offensive-adjectives-expanded-$code.csv with " . count($adjectives) . " adjectives\n";
}

echo "\nDone! Generated expanded adjectives with proper gender, number, and person relevance columns.\n";
