<?php

return [
    'insultos_personales' => [
        'cerda',
        'cerdo',
        'chancho',
        'idiota',
        'imbécil',
        'retrasado',
        'tarado',
        'mongol',
        'subnormal',
        'débil mental',
        'cretino',
        'zopenco',
        'papanatas',
        'pazguato',
        'bobo',
        'tonto',
        'simple',
    ],
    'insultos_corporales' => [
        'jorobado',
        'cojo',
        'ciego',
        'sordo',
        'mudo',
        'enano',
        'gigante deformado',
        'deforme',
        'contrahecho',
        'tullido',
        'paralítico',
    ],
    'insultos_morales' => [
        'bastardo',
        'hijo de puta',
        'desgraciado',
        'canalla',
        'sinvergüenza',
        'ladrón',
        'asesino',
        'violador',
        'maricón',
        'marica',
        'lesbiana',
        'puta',
        'prostituta',
    ],
    'insultos_apariencia' => [
        'feo',
        'horrible',
        'repugnante',
        'asqueroso',
        'nauseabundo',
        'gordo',
        'obeso',
        'flaco',
        'escuálido',
        'pálido',
        'negro',
        'indio',
        'gitano',
        'judío',
        'árabe',
        'chino',
        'japonés',
    ],
    'insultos_capacidad' => [
        'zurdo',
        'ambidextro',
        'patizambo',
        'zambo',
        'estrabismo',
        'bizco',
        'tuerto',
    ],
    'burlas_ridiculas' => [
        'viejalete',
        'vejestorio',
        'momia',
        'esqueleto',
        'saco de huesos',
        'arruinado',
        'decrépit',
        'senil',
        'chocho',
        'aniñado',
        'infantil',
        'pueril',
        'inmaduro',
    ],
    'palabras_soeces' => [
        'mierda',
        'caca',
        'vómito',
        'orín',
        'pis',
        'culo',
        'trasero',
        'ano',
        'pene',
        'verga',
        'polla',
        'coño',
        'vagina',
        'teta',
        'tit',
        'mama',
    ],
    'insultos_inteligencia' => [
        'analfabeto',
        'ignorante',
        'burro',
        'asno',
        'estúpido',
        'torpe',
        'lento',
        'despistado',
        'olvidadizo',
    ],
    'insultos_comportamiento' => [
        'mentiroso',
        'tramposo',
        'fraude',
        'defraudador',
        'estafador',
        'corrupto',
        'sobornado',
        'codicioso',
        'avaro',
        'tacaño',
        'egoísta',
        'cruel',
        'sádico',
    ],
];
