<?php

declare(strict_types=1);

/**
 * Catalogo de referencia: monedas (ISO 4217) y paises (ISO 3166-1).
 *
 * tasa_a_usd = cuantos USD vale 1 unidad de esa moneda (monto * tasa_a_usd
 * da el equivalente en USD). Son tasas estaticas ilustrativas para poder
 * consolidar reportes multi-moneda en este sistema de ejemplo -- en
 * produccion conviene refrescarlas desde un proveedor de tipo de cambio.
 *
 * @return array{monedas: array<string, array{nombre: string, simbolo: string, tasa_a_usd: float}>,
 *               paises: array<string, array{nombre: string, moneda: string}>}
 */
function catalogoPaisesMonedas(): array
{
    $monedas = [
        'USD' => ['nombre' => 'Dolar estadounidense', 'simbolo' => '$', 'tasa_a_usd' => 1.0],
        'CAD' => ['nombre' => 'Dolar canadiense', 'simbolo' => 'CA$', 'tasa_a_usd' => 0.73],
        'MXN' => ['nombre' => 'Peso mexicano', 'simbolo' => 'MX$', 'tasa_a_usd' => 0.058],
        'GTQ' => ['nombre' => 'Quetzal guatemalteco', 'simbolo' => 'Q', 'tasa_a_usd' => 0.13],
        'BZD' => ['nombre' => 'Dolar beliceno', 'simbolo' => 'BZ$', 'tasa_a_usd' => 0.50],
        'HNL' => ['nombre' => 'Lempira hondureno', 'simbolo' => 'L', 'tasa_a_usd' => 0.040],
        'NIO' => ['nombre' => 'Cordoba nicaraguense', 'simbolo' => 'C$', 'tasa_a_usd' => 0.027],
        'CRC' => ['nombre' => 'Colon costarricense', 'simbolo' => '₡', 'tasa_a_usd' => 0.0019],
        'PAB' => ['nombre' => 'Balboa panameno', 'simbolo' => 'B/.', 'tasa_a_usd' => 1.0],
        'CUP' => ['nombre' => 'Peso cubano', 'simbolo' => '$', 'tasa_a_usd' => 0.042],
        'DOP' => ['nombre' => 'Peso dominicano', 'simbolo' => 'RD$', 'tasa_a_usd' => 0.0167],
        'HTG' => ['nombre' => 'Gourde haitiano', 'simbolo' => 'G', 'tasa_a_usd' => 0.0076],
        'JMD' => ['nombre' => 'Dolar jamaiquino', 'simbolo' => 'J$', 'tasa_a_usd' => 0.0064],
        'TTD' => ['nombre' => 'Dolar de Trinidad y Tobago', 'simbolo' => 'TT$', 'tasa_a_usd' => 0.147],
        'BSD' => ['nombre' => 'Dolar bahameno', 'simbolo' => 'B$', 'tasa_a_usd' => 1.0],
        'BBD' => ['nombre' => 'Dolar de Barbados', 'simbolo' => 'Bds$', 'tasa_a_usd' => 0.50],
        'XCD' => ['nombre' => 'Dolar del Caribe Oriental', 'simbolo' => 'EC$', 'tasa_a_usd' => 0.37],
        'COP' => ['nombre' => 'Peso colombiano', 'simbolo' => 'CO$', 'tasa_a_usd' => 0.00025],
        'VES' => ['nombre' => 'Bolivar venezolano', 'simbolo' => 'Bs.', 'tasa_a_usd' => 0.027],
        'PEN' => ['nombre' => 'Sol peruano', 'simbolo' => 'S/', 'tasa_a_usd' => 0.27],
        'BOB' => ['nombre' => 'Boliviano', 'simbolo' => 'Bs', 'tasa_a_usd' => 0.145],
        'BRL' => ['nombre' => 'Real brasileno', 'simbolo' => 'R$', 'tasa_a_usd' => 0.20],
        'PYG' => ['nombre' => 'Guarani paraguayo', 'simbolo' => '₲', 'tasa_a_usd' => 0.00013],
        'UYU' => ['nombre' => 'Peso uruguayo', 'simbolo' => '$U', 'tasa_a_usd' => 0.025],
        'ARS' => ['nombre' => 'Peso argentino', 'simbolo' => 'AR$', 'tasa_a_usd' => 0.0008],
        'CLP' => ['nombre' => 'Peso chileno', 'simbolo' => 'CL$', 'tasa_a_usd' => 0.0010],
        'GYD' => ['nombre' => 'Dolar guyanes', 'simbolo' => 'G$', 'tasa_a_usd' => 0.0048],
        'SRD' => ['nombre' => 'Dolar surinames', 'simbolo' => 'Sr$', 'tasa_a_usd' => 0.028],
        'EUR' => ['nombre' => 'Euro', 'simbolo' => '€', 'tasa_a_usd' => 1.08],
        'GBP' => ['nombre' => 'Libra esterlina', 'simbolo' => '£', 'tasa_a_usd' => 1.27],
        'CHF' => ['nombre' => 'Franco suizo', 'simbolo' => 'CHF', 'tasa_a_usd' => 1.13],
        'NOK' => ['nombre' => 'Corona noruega', 'simbolo' => 'kr', 'tasa_a_usd' => 0.092],
        'SEK' => ['nombre' => 'Corona sueca', 'simbolo' => 'kr', 'tasa_a_usd' => 0.095],
        'DKK' => ['nombre' => 'Corona danesa', 'simbolo' => 'kr', 'tasa_a_usd' => 0.145],
        'ISK' => ['nombre' => 'Corona islandesa', 'simbolo' => 'kr', 'tasa_a_usd' => 0.0072],
        'PLN' => ['nombre' => 'Zloty polaco', 'simbolo' => 'zł', 'tasa_a_usd' => 0.25],
        'CZK' => ['nombre' => 'Corona checa', 'simbolo' => 'Kč', 'tasa_a_usd' => 0.043],
        'HUF' => ['nombre' => 'Forinto hungaro', 'simbolo' => 'Ft', 'tasa_a_usd' => 0.0027],
        'RON' => ['nombre' => 'Leu rumano', 'simbolo' => 'lei', 'tasa_a_usd' => 0.22],
        'BGN' => ['nombre' => 'Lev bulgaro', 'simbolo' => 'лв', 'tasa_a_usd' => 0.55],
        'RSD' => ['nombre' => 'Dinar serbio', 'simbolo' => 'дин', 'tasa_a_usd' => 0.0092],
        'BAM' => ['nombre' => 'Marco convertible', 'simbolo' => 'KM', 'tasa_a_usd' => 0.55],
        'MKD' => ['nombre' => 'Denar macedonio', 'simbolo' => 'ден', 'tasa_a_usd' => 0.018],
        'ALL' => ['nombre' => 'Lek albanes', 'simbolo' => 'L', 'tasa_a_usd' => 0.011],
        'MDL' => ['nombre' => 'Leu moldavo', 'simbolo' => 'L', 'tasa_a_usd' => 0.056],
        'UAH' => ['nombre' => 'Grivna ucraniana', 'simbolo' => '₴', 'tasa_a_usd' => 0.024],
        'BYN' => ['nombre' => 'Rublo bielorruso', 'simbolo' => 'Br', 'tasa_a_usd' => 0.0031],
        'RUB' => ['nombre' => 'Rublo ruso', 'simbolo' => '₽', 'tasa_a_usd' => 0.010],
        'TRY' => ['nombre' => 'Lira turca', 'simbolo' => '₺', 'tasa_a_usd' => 0.029],
        'GEL' => ['nombre' => 'Lari georgiano', 'simbolo' => '₾', 'tasa_a_usd' => 0.37],
        'AMD' => ['nombre' => 'Dram armenio', 'simbolo' => '֏', 'tasa_a_usd' => 0.0026],
        'AZN' => ['nombre' => 'Manat azerbaiyano', 'simbolo' => '₼', 'tasa_a_usd' => 0.59],
        'EGP' => ['nombre' => 'Libra egipcia', 'simbolo' => 'E£', 'tasa_a_usd' => 0.020],
        'LYD' => ['nombre' => 'Dinar libio', 'simbolo' => 'ل.د', 'tasa_a_usd' => 0.206],
        'TND' => ['nombre' => 'Dinar tunecino', 'simbolo' => 'د.ت', 'tasa_a_usd' => 0.32],
        'DZD' => ['nombre' => 'Dinar argelino', 'simbolo' => 'د.ج', 'tasa_a_usd' => 0.0075],
        'MAD' => ['nombre' => 'Dirham marroqui', 'simbolo' => 'د.م.', 'tasa_a_usd' => 0.099],
        'SDG' => ['nombre' => 'Libra sudanesa', 'simbolo' => 'ج.س.', 'tasa_a_usd' => 0.0017],
        'SSP' => ['nombre' => 'Libra sursudanesa', 'simbolo' => 'SSP', 'tasa_a_usd' => 0.0008],
        'ETB' => ['nombre' => 'Birr etiope', 'simbolo' => 'Br', 'tasa_a_usd' => 0.0088],
        'ERN' => ['nombre' => 'Nakfa eritreo', 'simbolo' => 'Nfk', 'tasa_a_usd' => 0.067],
        'DJF' => ['nombre' => 'Franco yibutiano', 'simbolo' => 'Fdj', 'tasa_a_usd' => 0.0056],
        'SOS' => ['nombre' => 'Chelin somali', 'simbolo' => 'Sh', 'tasa_a_usd' => 0.0017],
        'KES' => ['nombre' => 'Chelin keniano', 'simbolo' => 'KSh', 'tasa_a_usd' => 0.0078],
        'UGX' => ['nombre' => 'Chelin ugandes', 'simbolo' => 'USh', 'tasa_a_usd' => 0.00027],
        'TZS' => ['nombre' => 'Chelin tanzano', 'simbolo' => 'TSh', 'tasa_a_usd' => 0.00039],
        'RWF' => ['nombre' => 'Franco ruandes', 'simbolo' => 'FRw', 'tasa_a_usd' => 0.00071],
        'BIF' => ['nombre' => 'Franco burundes', 'simbolo' => 'FBu', 'tasa_a_usd' => 0.00035],
        'CDF' => ['nombre' => 'Franco congoleno', 'simbolo' => 'FC', 'tasa_a_usd' => 0.00035],
        'XAF' => ['nombre' => 'Franco CFA (Africa Central)', 'simbolo' => 'FCFA', 'tasa_a_usd' => 0.00165],
        'NGN' => ['nombre' => 'Naira nigeriana', 'simbolo' => '₦', 'tasa_a_usd' => 0.00062],
        'GHS' => ['nombre' => 'Cedi ghanes', 'simbolo' => 'GH₵', 'tasa_a_usd' => 0.068],
        'XOF' => ['nombre' => 'Franco CFA (Africa Occidental)', 'simbolo' => 'CFA', 'tasa_a_usd' => 0.00165],
        'GNF' => ['nombre' => 'Franco guineano', 'simbolo' => 'FG', 'tasa_a_usd' => 0.00012],
        'SLE' => ['nombre' => 'Leone (nuevo)', 'simbolo' => 'Le', 'tasa_a_usd' => 0.044],
        'LRD' => ['nombre' => 'Dolar liberiano', 'simbolo' => 'L$', 'tasa_a_usd' => 0.0052],
        'GMD' => ['nombre' => 'Dalasi gambiano', 'simbolo' => 'D', 'tasa_a_usd' => 0.014],
        'CVE' => ['nombre' => 'Escudo caboverdiano', 'simbolo' => '$', 'tasa_a_usd' => 0.0098],
        'MRU' => ['nombre' => 'Uguiya mauritana', 'simbolo' => 'UM', 'tasa_a_usd' => 0.025],
        'ZAR' => ['nombre' => 'Rand sudafricano', 'simbolo' => 'R', 'tasa_a_usd' => 0.054],
        'NAD' => ['nombre' => 'Dolar namibio', 'simbolo' => 'N$', 'tasa_a_usd' => 0.054],
        'BWP' => ['nombre' => 'Pula botsuanesa', 'simbolo' => 'P', 'tasa_a_usd' => 0.074],
        'ZWL' => ['nombre' => 'Dolar zimbabuense', 'simbolo' => 'Z$', 'tasa_a_usd' => 0.0027],
        'ZMW' => ['nombre' => 'Kwacha zambiano', 'simbolo' => 'ZK', 'tasa_a_usd' => 0.037],
        'MWK' => ['nombre' => 'Kwacha malawiano', 'simbolo' => 'MK', 'tasa_a_usd' => 0.00058],
        'MZN' => ['nombre' => 'Metical mozambiqueno', 'simbolo' => 'MT', 'tasa_a_usd' => 0.0157],
        'AOA' => ['nombre' => 'Kwanza angoleno', 'simbolo' => 'Kz', 'tasa_a_usd' => 0.0011],
        'SZL' => ['nombre' => 'Lilangeni suazi', 'simbolo' => 'L', 'tasa_a_usd' => 0.054],
        'LSL' => ['nombre' => 'Loti lesotense', 'simbolo' => 'L', 'tasa_a_usd' => 0.054],
        'MGA' => ['nombre' => 'Ariary malgache', 'simbolo' => 'Ar', 'tasa_a_usd' => 0.00022],
        'MUR' => ['nombre' => 'Rupia mauriciana', 'simbolo' => '₨', 'tasa_a_usd' => 0.021],
        'SCR' => ['nombre' => 'Rupia seychellense', 'simbolo' => '₨', 'tasa_a_usd' => 0.072],
        'KMF' => ['nombre' => 'Franco comorense', 'simbolo' => 'CF', 'tasa_a_usd' => 0.0022],
        'STN' => ['nombre' => 'Dobra santotomense', 'simbolo' => 'Db', 'tasa_a_usd' => 0.043],
        'SAR' => ['nombre' => 'Riyal saudi', 'simbolo' => '﷼', 'tasa_a_usd' => 0.267],
        'AED' => ['nombre' => 'Dirham de EAU', 'simbolo' => 'د.إ', 'tasa_a_usd' => 0.272],
        'QAR' => ['nombre' => 'Riyal catari', 'simbolo' => 'ر.ق', 'tasa_a_usd' => 0.2747],
        'KWD' => ['nombre' => 'Dinar kuwaiti', 'simbolo' => 'د.ك', 'tasa_a_usd' => 3.25],
        'BHD' => ['nombre' => 'Dinar bahreini', 'simbolo' => '.د.ب', 'tasa_a_usd' => 2.65],
        'OMR' => ['nombre' => 'Rial omani', 'simbolo' => 'ر.ع.', 'tasa_a_usd' => 2.60],
        'YER' => ['nombre' => 'Rial yemeni', 'simbolo' => '﷼', 'tasa_a_usd' => 0.0040],
        'IQD' => ['nombre' => 'Dinar iraqui', 'simbolo' => 'ع.د', 'tasa_a_usd' => 0.00076],
        'IRR' => ['nombre' => 'Rial irani', 'simbolo' => '﷼', 'tasa_a_usd' => 0.000024],
        'SYP' => ['nombre' => 'Libra siria', 'simbolo' => '£S', 'tasa_a_usd' => 0.00008],
        'JOD' => ['nombre' => 'Dinar jordano', 'simbolo' => 'د.ا', 'tasa_a_usd' => 1.41],
        'LBP' => ['nombre' => 'Libra libanesa', 'simbolo' => 'ل.ل', 'tasa_a_usd' => 0.0000112],
        'ILS' => ['nombre' => 'Nuevo shekel israeli', 'simbolo' => '₪', 'tasa_a_usd' => 0.27],
        'KZT' => ['nombre' => 'Tenge kazajo', 'simbolo' => '₸', 'tasa_a_usd' => 0.0021],
        'UZS' => ['nombre' => 'Som uzbeko', 'simbolo' => 'so\'m', 'tasa_a_usd' => 0.000078],
        'TMT' => ['nombre' => 'Manat turcomano', 'simbolo' => 'm', 'tasa_a_usd' => 0.286],
        'TJS' => ['nombre' => 'Somoni tayiko', 'simbolo' => 'SM', 'tasa_a_usd' => 0.094],
        'KGS' => ['nombre' => 'Som kirguizo', 'simbolo' => 'с', 'tasa_a_usd' => 0.0115],
        'AFN' => ['nombre' => 'Afgani afgano', 'simbolo' => '؋', 'tasa_a_usd' => 0.0142],
        'INR' => ['nombre' => 'Rupia india', 'simbolo' => '₹', 'tasa_a_usd' => 0.012],
        'PKR' => ['nombre' => 'Rupia pakistani', 'simbolo' => '₨', 'tasa_a_usd' => 0.0036],
        'BDT' => ['nombre' => 'Taka bangladesi', 'simbolo' => '৳', 'tasa_a_usd' => 0.0084],
        'LKR' => ['nombre' => 'Rupia esrilanquesa', 'simbolo' => '₨', 'tasa_a_usd' => 0.0034],
        'NPR' => ['nombre' => 'Rupia nepali', 'simbolo' => '₨', 'tasa_a_usd' => 0.0075],
        'BTN' => ['nombre' => 'Ngultrum butanes', 'simbolo' => 'Nu.', 'tasa_a_usd' => 0.012],
        'MVR' => ['nombre' => 'Rufiyaa maldiva', 'simbolo' => 'Rf', 'tasa_a_usd' => 0.065],
        'CNY' => ['nombre' => 'Yuan chino', 'simbolo' => '¥', 'tasa_a_usd' => 0.14],
        'JPY' => ['nombre' => 'Yen japones', 'simbolo' => '¥', 'tasa_a_usd' => 0.0067],
        'KRW' => ['nombre' => 'Won surcoreano', 'simbolo' => '₩', 'tasa_a_usd' => 0.00072],
        'KPW' => ['nombre' => 'Won norcoreano', 'simbolo' => '₩', 'tasa_a_usd' => 0.0011],
        'MNT' => ['nombre' => 'Tugrik mongol', 'simbolo' => '₮', 'tasa_a_usd' => 0.00029],
        'TWD' => ['nombre' => 'Nuevo dolar taiwanes', 'simbolo' => 'NT$', 'tasa_a_usd' => 0.031],
        'HKD' => ['nombre' => 'Dolar de Hong Kong', 'simbolo' => 'HK$', 'tasa_a_usd' => 0.128],
        'MOP' => ['nombre' => 'Pataca de Macao', 'simbolo' => 'MOP$', 'tasa_a_usd' => 0.124],
        'THB' => ['nombre' => 'Baht tailandes', 'simbolo' => '฿', 'tasa_a_usd' => 0.028],
        'VND' => ['nombre' => 'Dong vietnamita', 'simbolo' => '₫', 'tasa_a_usd' => 0.00004],
        'IDR' => ['nombre' => 'Rupia indonesia', 'simbolo' => 'Rp', 'tasa_a_usd' => 0.000062],
        'MYR' => ['nombre' => 'Ringgit malayo', 'simbolo' => 'RM', 'tasa_a_usd' => 0.21],
        'SGD' => ['nombre' => 'Dolar de Singapur', 'simbolo' => 'S$', 'tasa_a_usd' => 0.74],
        'PHP' => ['nombre' => 'Peso filipino', 'simbolo' => '₱', 'tasa_a_usd' => 0.017],
        'MMK' => ['nombre' => 'Kyat birmano', 'simbolo' => 'K', 'tasa_a_usd' => 0.00048],
        'KHR' => ['nombre' => 'Riel camboyano', 'simbolo' => '៛', 'tasa_a_usd' => 0.00025],
        'LAK' => ['nombre' => 'Kip laosiano', 'simbolo' => '₭', 'tasa_a_usd' => 0.000046],
        'BND' => ['nombre' => 'Dolar de Brunei', 'simbolo' => 'B$', 'tasa_a_usd' => 0.74],
        'AUD' => ['nombre' => 'Dolar australiano', 'simbolo' => 'A$', 'tasa_a_usd' => 0.65],
        'NZD' => ['nombre' => 'Dolar neozelandes', 'simbolo' => 'NZ$', 'tasa_a_usd' => 0.60],
        'PGK' => ['nombre' => 'Kina papuana', 'simbolo' => 'K', 'tasa_a_usd' => 0.25],
        'FJD' => ['nombre' => 'Dolar fiyiano', 'simbolo' => 'FJ$', 'tasa_a_usd' => 0.44],
        'SBD' => ['nombre' => 'Dolar salomonense', 'simbolo' => 'SI$', 'tasa_a_usd' => 0.12],
        'VUV' => ['nombre' => 'Vatu vanuatuense', 'simbolo' => 'VT', 'tasa_a_usd' => 0.0084],
        'WST' => ['nombre' => 'Tala samoana', 'simbolo' => 'WS$', 'tasa_a_usd' => 0.37],
        'TOP' => ['nombre' => 'Paanga tongana', 'simbolo' => 'T$', 'tasa_a_usd' => 0.42],
    ];

    $paises = [
        // America del Norte
        'US' => ['nombre' => 'Estados Unidos', 'moneda' => 'USD'],
        'CA' => ['nombre' => 'Canada', 'moneda' => 'CAD'],
        'MX' => ['nombre' => 'Mexico', 'moneda' => 'MXN'],
        // America Central
        'GT' => ['nombre' => 'Guatemala', 'moneda' => 'GTQ'],
        'BZ' => ['nombre' => 'Belice', 'moneda' => 'BZD'],
        'HN' => ['nombre' => 'Honduras', 'moneda' => 'HNL'],
        'SV' => ['nombre' => 'El Salvador', 'moneda' => 'USD'],
        'NI' => ['nombre' => 'Nicaragua', 'moneda' => 'NIO'],
        'CR' => ['nombre' => 'Costa Rica', 'moneda' => 'CRC'],
        'PA' => ['nombre' => 'Panama', 'moneda' => 'PAB'],
        // Caribe
        'CU' => ['nombre' => 'Cuba', 'moneda' => 'CUP'],
        'DO' => ['nombre' => 'Republica Dominicana', 'moneda' => 'DOP'],
        'HT' => ['nombre' => 'Haiti', 'moneda' => 'HTG'],
        'JM' => ['nombre' => 'Jamaica', 'moneda' => 'JMD'],
        'TT' => ['nombre' => 'Trinidad y Tobago', 'moneda' => 'TTD'],
        'BS' => ['nombre' => 'Bahamas', 'moneda' => 'BSD'],
        'BB' => ['nombre' => 'Barbados', 'moneda' => 'BBD'],
        'GD' => ['nombre' => 'Granada', 'moneda' => 'XCD'],
        'LC' => ['nombre' => 'Santa Lucia', 'moneda' => 'XCD'],
        'VC' => ['nombre' => 'San Vicente y las Granadinas', 'moneda' => 'XCD'],
        'AG' => ['nombre' => 'Antigua y Barbuda', 'moneda' => 'XCD'],
        'KN' => ['nombre' => 'San Cristobal y Nieves', 'moneda' => 'XCD'],
        'DM' => ['nombre' => 'Dominica', 'moneda' => 'XCD'],
        // America del Sur
        'CO' => ['nombre' => 'Colombia', 'moneda' => 'COP'],
        'VE' => ['nombre' => 'Venezuela', 'moneda' => 'VES'],
        'EC' => ['nombre' => 'Ecuador', 'moneda' => 'USD'],
        'PE' => ['nombre' => 'Peru', 'moneda' => 'PEN'],
        'BO' => ['nombre' => 'Bolivia', 'moneda' => 'BOB'],
        'BR' => ['nombre' => 'Brasil', 'moneda' => 'BRL'],
        'PY' => ['nombre' => 'Paraguay', 'moneda' => 'PYG'],
        'UY' => ['nombre' => 'Uruguay', 'moneda' => 'UYU'],
        'AR' => ['nombre' => 'Argentina', 'moneda' => 'ARS'],
        'CL' => ['nombre' => 'Chile', 'moneda' => 'CLP'],
        'GY' => ['nombre' => 'Guyana', 'moneda' => 'GYD'],
        'SR' => ['nombre' => 'Surinam', 'moneda' => 'SRD'],
        // Europa (zona euro)
        'ES' => ['nombre' => 'Espana', 'moneda' => 'EUR'],
        'PT' => ['nombre' => 'Portugal', 'moneda' => 'EUR'],
        'FR' => ['nombre' => 'Francia', 'moneda' => 'EUR'],
        'DE' => ['nombre' => 'Alemania', 'moneda' => 'EUR'],
        'IT' => ['nombre' => 'Italia', 'moneda' => 'EUR'],
        'NL' => ['nombre' => 'Paises Bajos', 'moneda' => 'EUR'],
        'BE' => ['nombre' => 'Belgica', 'moneda' => 'EUR'],
        'AT' => ['nombre' => 'Austria', 'moneda' => 'EUR'],
        'IE' => ['nombre' => 'Irlanda', 'moneda' => 'EUR'],
        'GR' => ['nombre' => 'Grecia', 'moneda' => 'EUR'],
        'FI' => ['nombre' => 'Finlandia', 'moneda' => 'EUR'],
        'LU' => ['nombre' => 'Luxemburgo', 'moneda' => 'EUR'],
        'MT' => ['nombre' => 'Malta', 'moneda' => 'EUR'],
        'CY' => ['nombre' => 'Chipre', 'moneda' => 'EUR'],
        'SI' => ['nombre' => 'Eslovenia', 'moneda' => 'EUR'],
        'SK' => ['nombre' => 'Eslovaquia', 'moneda' => 'EUR'],
        'EE' => ['nombre' => 'Estonia', 'moneda' => 'EUR'],
        'LV' => ['nombre' => 'Letonia', 'moneda' => 'EUR'],
        'LT' => ['nombre' => 'Lituania', 'moneda' => 'EUR'],
        'HR' => ['nombre' => 'Croacia', 'moneda' => 'EUR'],
        'AD' => ['nombre' => 'Andorra', 'moneda' => 'EUR'],
        'MC' => ['nombre' => 'Monaco', 'moneda' => 'EUR'],
        'SM' => ['nombre' => 'San Marino', 'moneda' => 'EUR'],
        'VA' => ['nombre' => 'Ciudad del Vaticano', 'moneda' => 'EUR'],
        'ME' => ['nombre' => 'Montenegro', 'moneda' => 'EUR'],
        'XK' => ['nombre' => 'Kosovo', 'moneda' => 'EUR'],
        // Europa (no euro)
        'GB' => ['nombre' => 'Reino Unido', 'moneda' => 'GBP'],
        'CH' => ['nombre' => 'Suiza', 'moneda' => 'CHF'],
        'NO' => ['nombre' => 'Noruega', 'moneda' => 'NOK'],
        'SE' => ['nombre' => 'Suecia', 'moneda' => 'SEK'],
        'DK' => ['nombre' => 'Dinamarca', 'moneda' => 'DKK'],
        'IS' => ['nombre' => 'Islandia', 'moneda' => 'ISK'],
        'PL' => ['nombre' => 'Polonia', 'moneda' => 'PLN'],
        'CZ' => ['nombre' => 'Republica Checa', 'moneda' => 'CZK'],
        'HU' => ['nombre' => 'Hungria', 'moneda' => 'HUF'],
        'RO' => ['nombre' => 'Rumania', 'moneda' => 'RON'],
        'BG' => ['nombre' => 'Bulgaria', 'moneda' => 'BGN'],
        'RS' => ['nombre' => 'Serbia', 'moneda' => 'RSD'],
        'BA' => ['nombre' => 'Bosnia y Herzegovina', 'moneda' => 'BAM'],
        'MK' => ['nombre' => 'Macedonia del Norte', 'moneda' => 'MKD'],
        'AL' => ['nombre' => 'Albania', 'moneda' => 'ALL'],
        'MD' => ['nombre' => 'Moldavia', 'moneda' => 'MDL'],
        'UA' => ['nombre' => 'Ucrania', 'moneda' => 'UAH'],
        'BY' => ['nombre' => 'Bielorrusia', 'moneda' => 'BYN'],
        'RU' => ['nombre' => 'Rusia', 'moneda' => 'RUB'],
        'TR' => ['nombre' => 'Turquia', 'moneda' => 'TRY'],
        'GE' => ['nombre' => 'Georgia', 'moneda' => 'GEL'],
        'AM' => ['nombre' => 'Armenia', 'moneda' => 'AMD'],
        'AZ' => ['nombre' => 'Azerbaiyan', 'moneda' => 'AZN'],
        // Africa
        'EG' => ['nombre' => 'Egipto', 'moneda' => 'EGP'],
        'LY' => ['nombre' => 'Libia', 'moneda' => 'LYD'],
        'TN' => ['nombre' => 'Tunez', 'moneda' => 'TND'],
        'DZ' => ['nombre' => 'Argelia', 'moneda' => 'DZD'],
        'MA' => ['nombre' => 'Marruecos', 'moneda' => 'MAD'],
        'SD' => ['nombre' => 'Sudan', 'moneda' => 'SDG'],
        'SS' => ['nombre' => 'Sudan del Sur', 'moneda' => 'SSP'],
        'ET' => ['nombre' => 'Etiopia', 'moneda' => 'ETB'],
        'ER' => ['nombre' => 'Eritrea', 'moneda' => 'ERN'],
        'DJ' => ['nombre' => 'Yibuti', 'moneda' => 'DJF'],
        'SO' => ['nombre' => 'Somalia', 'moneda' => 'SOS'],
        'KE' => ['nombre' => 'Kenia', 'moneda' => 'KES'],
        'UG' => ['nombre' => 'Uganda', 'moneda' => 'UGX'],
        'TZ' => ['nombre' => 'Tanzania', 'moneda' => 'TZS'],
        'RW' => ['nombre' => 'Ruanda', 'moneda' => 'RWF'],
        'BI' => ['nombre' => 'Burundi', 'moneda' => 'BIF'],
        'CD' => ['nombre' => 'Republica Democratica del Congo', 'moneda' => 'CDF'],
        'CG' => ['nombre' => 'Republica del Congo', 'moneda' => 'XAF'],
        'CM' => ['nombre' => 'Camerun', 'moneda' => 'XAF'],
        'CF' => ['nombre' => 'Republica Centroafricana', 'moneda' => 'XAF'],
        'TD' => ['nombre' => 'Chad', 'moneda' => 'XAF'],
        'GA' => ['nombre' => 'Gabon', 'moneda' => 'XAF'],
        'GQ' => ['nombre' => 'Guinea Ecuatorial', 'moneda' => 'XAF'],
        'NG' => ['nombre' => 'Nigeria', 'moneda' => 'NGN'],
        'GH' => ['nombre' => 'Ghana', 'moneda' => 'GHS'],
        'CI' => ['nombre' => 'Costa de Marfil', 'moneda' => 'XOF'],
        'SN' => ['nombre' => 'Senegal', 'moneda' => 'XOF'],
        'ML' => ['nombre' => 'Mali', 'moneda' => 'XOF'],
        'BF' => ['nombre' => 'Burkina Faso', 'moneda' => 'XOF'],
        'NE' => ['nombre' => 'Niger', 'moneda' => 'XOF'],
        'TG' => ['nombre' => 'Togo', 'moneda' => 'XOF'],
        'BJ' => ['nombre' => 'Benin', 'moneda' => 'XOF'],
        'GW' => ['nombre' => 'Guinea-Bisau', 'moneda' => 'XOF'],
        'GN' => ['nombre' => 'Guinea', 'moneda' => 'GNF'],
        'SL' => ['nombre' => 'Sierra Leona', 'moneda' => 'SLE'],
        'LR' => ['nombre' => 'Liberia', 'moneda' => 'LRD'],
        'GM' => ['nombre' => 'Gambia', 'moneda' => 'GMD'],
        'CV' => ['nombre' => 'Cabo Verde', 'moneda' => 'CVE'],
        'MR' => ['nombre' => 'Mauritania', 'moneda' => 'MRU'],
        'ZA' => ['nombre' => 'Sudafrica', 'moneda' => 'ZAR'],
        'NA' => ['nombre' => 'Namibia', 'moneda' => 'NAD'],
        'BW' => ['nombre' => 'Botsuana', 'moneda' => 'BWP'],
        'ZW' => ['nombre' => 'Zimbabue', 'moneda' => 'ZWL'],
        'ZM' => ['nombre' => 'Zambia', 'moneda' => 'ZMW'],
        'MW' => ['nombre' => 'Malaui', 'moneda' => 'MWK'],
        'MZ' => ['nombre' => 'Mozambique', 'moneda' => 'MZN'],
        'AO' => ['nombre' => 'Angola', 'moneda' => 'AOA'],
        'SZ' => ['nombre' => 'Esuatini', 'moneda' => 'SZL'],
        'LS' => ['nombre' => 'Lesoto', 'moneda' => 'LSL'],
        'MG' => ['nombre' => 'Madagascar', 'moneda' => 'MGA'],
        'MU' => ['nombre' => 'Mauricio', 'moneda' => 'MUR'],
        'SC' => ['nombre' => 'Seychelles', 'moneda' => 'SCR'],
        'KM' => ['nombre' => 'Comoras', 'moneda' => 'KMF'],
        'ST' => ['nombre' => 'Santo Tome y Principe', 'moneda' => 'STN'],
        // Oriente Medio
        'SA' => ['nombre' => 'Arabia Saudita', 'moneda' => 'SAR'],
        'AE' => ['nombre' => 'Emiratos Arabes Unidos', 'moneda' => 'AED'],
        'QA' => ['nombre' => 'Catar', 'moneda' => 'QAR'],
        'KW' => ['nombre' => 'Kuwait', 'moneda' => 'KWD'],
        'BH' => ['nombre' => 'Bahrein', 'moneda' => 'BHD'],
        'OM' => ['nombre' => 'Oman', 'moneda' => 'OMR'],
        'YE' => ['nombre' => 'Yemen', 'moneda' => 'YER'],
        'IQ' => ['nombre' => 'Irak', 'moneda' => 'IQD'],
        'IR' => ['nombre' => 'Iran', 'moneda' => 'IRR'],
        'SY' => ['nombre' => 'Siria', 'moneda' => 'SYP'],
        'JO' => ['nombre' => 'Jordania', 'moneda' => 'JOD'],
        'LB' => ['nombre' => 'Libano', 'moneda' => 'LBP'],
        'IL' => ['nombre' => 'Israel', 'moneda' => 'ILS'],
        'PS' => ['nombre' => 'Palestina', 'moneda' => 'ILS'],
        // Asia Central
        'KZ' => ['nombre' => 'Kazajistan', 'moneda' => 'KZT'],
        'UZ' => ['nombre' => 'Uzbekistan', 'moneda' => 'UZS'],
        'TM' => ['nombre' => 'Turkmenistan', 'moneda' => 'TMT'],
        'TJ' => ['nombre' => 'Tayikistan', 'moneda' => 'TJS'],
        'KG' => ['nombre' => 'Kirguistan', 'moneda' => 'KGS'],
        'AF' => ['nombre' => 'Afganistan', 'moneda' => 'AFN'],
        // Asia del Sur
        'IN' => ['nombre' => 'India', 'moneda' => 'INR'],
        'PK' => ['nombre' => 'Pakistan', 'moneda' => 'PKR'],
        'BD' => ['nombre' => 'Bangladesh', 'moneda' => 'BDT'],
        'LK' => ['nombre' => 'Sri Lanka', 'moneda' => 'LKR'],
        'NP' => ['nombre' => 'Nepal', 'moneda' => 'NPR'],
        'BT' => ['nombre' => 'Butan', 'moneda' => 'BTN'],
        'MV' => ['nombre' => 'Maldivas', 'moneda' => 'MVR'],
        // Asia Oriental
        'CN' => ['nombre' => 'China', 'moneda' => 'CNY'],
        'JP' => ['nombre' => 'Japon', 'moneda' => 'JPY'],
        'KR' => ['nombre' => 'Corea del Sur', 'moneda' => 'KRW'],
        'KP' => ['nombre' => 'Corea del Norte', 'moneda' => 'KPW'],
        'MN' => ['nombre' => 'Mongolia', 'moneda' => 'MNT'],
        'TW' => ['nombre' => 'Taiwan', 'moneda' => 'TWD'],
        'HK' => ['nombre' => 'Hong Kong', 'moneda' => 'HKD'],
        'MO' => ['nombre' => 'Macao', 'moneda' => 'MOP'],
        // Sudeste asiatico
        'TH' => ['nombre' => 'Tailandia', 'moneda' => 'THB'],
        'VN' => ['nombre' => 'Vietnam', 'moneda' => 'VND'],
        'ID' => ['nombre' => 'Indonesia', 'moneda' => 'IDR'],
        'MY' => ['nombre' => 'Malasia', 'moneda' => 'MYR'],
        'SG' => ['nombre' => 'Singapur', 'moneda' => 'SGD'],
        'PH' => ['nombre' => 'Filipinas', 'moneda' => 'PHP'],
        'MM' => ['nombre' => 'Myanmar', 'moneda' => 'MMK'],
        'KH' => ['nombre' => 'Camboya', 'moneda' => 'KHR'],
        'LA' => ['nombre' => 'Laos', 'moneda' => 'LAK'],
        'BN' => ['nombre' => 'Brunei', 'moneda' => 'BND'],
        'TL' => ['nombre' => 'Timor Oriental', 'moneda' => 'USD'],
        // Oceania
        'AU' => ['nombre' => 'Australia', 'moneda' => 'AUD'],
        'NZ' => ['nombre' => 'Nueva Zelanda', 'moneda' => 'NZD'],
        'PG' => ['nombre' => 'Papua Nueva Guinea', 'moneda' => 'PGK'],
        'FJ' => ['nombre' => 'Fiyi', 'moneda' => 'FJD'],
        'SB' => ['nombre' => 'Islas Salomon', 'moneda' => 'SBD'],
        'VU' => ['nombre' => 'Vanuatu', 'moneda' => 'VUV'],
        'WS' => ['nombre' => 'Samoa', 'moneda' => 'WST'],
        'TO' => ['nombre' => 'Tonga', 'moneda' => 'TOP'],
        'KI' => ['nombre' => 'Kiribati', 'moneda' => 'AUD'],
        'TV' => ['nombre' => 'Tuvalu', 'moneda' => 'AUD'],
        'NR' => ['nombre' => 'Nauru', 'moneda' => 'AUD'],
        'FM' => ['nombre' => 'Micronesia', 'moneda' => 'USD'],
        'MH' => ['nombre' => 'Islas Marshall', 'moneda' => 'USD'],
        'PW' => ['nombre' => 'Palaos', 'moneda' => 'USD'],
    ];

    return ['monedas' => $monedas, 'paises' => $paises];
}
